pbload.o: pbload.c c:/djgpp/include/stdio.h \
 c:/djgpp/include/sys/djtypes.h c:/djgpp/include/stdlib.h \
 c:/djgpp/include/io.h c:/djgpp/include/sys/types.h \
 c:/djgpp/include/conio.h c:/djgpp/include/dos.h c:/djgpp/include/pc.h \
 c:/djgpp/include/inlines/pc.h c:/djgpp/include/process.h \
 c:/djgpp/include/signal.h c:/djgpp/include/string.h \
 c:/djgpp/include/sys/movedata.h c:/djgpp/include/time.h \
 c:/djgpp/include/bios.h c:/djgpp/include/unistd.h \
 /video/tools/putil/lib/pd.h
