pdir.o: pdir.c c:/djgpp/include/crt0.h c:/djgpp/include/stdlib.h \
 c:/djgpp/include/sys/djtypes.h c:/djgpp/include/string.h \
 c:/djgpp/include/sys/movedata.h c:/djgpp/include/stdio.h \
 c:/djgpp/include/dir.h c:/djgpp/include/ctype.h \
 c:/djgpp/include/inlines/ctype.ha c:/djgpp/include/inlines/ctype.hd \
 c:/djgpp/include/unistd.h c:/djgpp/include/sys/types.h \
 c:/djgpp/include/sys\stat.h c:/djgpp/include/fcntl.h \
 c:/djgpp/include/libc/dosio.h c:/djgpp/include/go32.h \
 c:/djgpp/include/sys/segments.h c:/djgpp/include/dpmi.h \
 c:/djgpp/include/errno.h c:/djgpp/include/dos.h c:/djgpp/include/pc.h \
 c:/djgpp/include/inlines/pc.h lib/pd.h
