#line 2 "cvtmod.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 23
#define YY_END_OF_BUFFER 24
static yyconst short int yy_accept[334] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   24,   22,
       22,   22,   22,    8,    8,    8,    8,    8,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,    0,    0,
        0,    2,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   18,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   19,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   10,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    6,    0,   12,    0,
        0,    0,    0,    0,    0,    0,    1,    9,    0,    0,
        0,    0,    6,    0,    0,    0,    0,    0,    0,    0,
       21,    0,    0,    0,    0,    0,    0,    0,    0,   13,
        0,    0,    0,    0,   20,    0,    0,    0,    0,    5,
        0,    0,    0,    7,    0,    6,    0,   13,    0,    0,

       16,    0,    0,   14,    0,    0,   17,    0,    0,   15,
        5,    0,    0,    0,    0,   16,   14,   17,   15,    0,
        0,    0,    0,    0,   13,    0,    0,    0,    0,    0,
        5,    0,    0,    0,    0,    0,   11,    0,   16,    0,
       14,    0,   17,    0,   15,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    3,    0,    0,    0,    3,    0,    0,    0,

        0,    0,    0,    3,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    4,    4,    0,
        0,    4,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    1,    1,    1,    6,
        7,    1,    8,    9,   10,   11,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,   13,    1,
       14,    1,    1,    1,   15,   15,   15,   15,   16,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
        1,    1,    1,    1,    5,    1,   17,   15,   18,   19,

       20,   21,   22,   23,   24,   15,   15,   25,   26,   27,
       28,   29,   15,   30,   31,   32,   33,   34,   15,   35,
       36,   15,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[37] =
    {   0,
        1,    2,    3,    2,    4,    5,    1,    1,    1,    1,
        1,    4,    1,    1,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6
    } ;

static yyconst short int yy_base[343] =
    {   0,
        0,    0,    4,    5,   13,   41,    1,    9,  647,  648,
      618,  622,  624,  648,  630,  608,  613,   21,  614,  609,
      610,   21,   22,  624,   26,  608,  612,   32,  609,  616,
      597,  648,  625,  605,  612,  622,  610,  598,  593,  603,
      603,  601,  601,  648,  595,  591,  582,  598,  584,  609,
      578,  594,    0,  590,  593,  593,  588,  579,  586,  577,
      577,  577,  572,  582,  568,    3,  578,  579,    6,  578,
      577,  564,  564,  574,  562,  572,  561,  568,  569,  558,
      557,    9,  574,   50,  557,  554,   13,  571,   55,  578,
      562,  560,  559,  561,  557,  559,  571,  648,  542,    1,

      553,   67,    5,  545,  567,   68,   24,  556,  536,  564,
      535,  534,  533,  532,  549,   87,   88,   91,   86,   95,
      558,  547,   92,   99,  551,  529,  544,  553,  552,  551,
      550,  549,  110,  111,  114,  540,   69,   46,  539,  108,
      544,  545,  536,   73,   57,  535,  110,  537,  536,  524,
      121,  529,  528,  527,  526,  533,  122,  125,  119,  128,
      532,  531,  121,  532,  132,  136,  143,  144,  147,  144,
      648,  144,  153,  148,    0,  158,  521,  150,  522,  160,
      165,  176,  179,  190,  648,  521,  170,  162,  520,  173,
      184,  519,  194,    0,  518,  517,  524,  192,  186,  514,

      198,  202,  508,  204,  206,  506,  208,  210,  503,  212,
      213,  218,  224,    0,  227,  220,  229,  230,  231,  244,
      245,  256,  504,  496,  492,  251,  261,  262,  267,  490,
      475,  474,  253,  269,  470,  273,  648,  458,  437,  430,
      426,  416,  412,  405,  376,  274,  274,  279,  291,  369,
      287,  286,  352,  293,  299,  348,  300,  347,  331,  302,
      306,  309,  327,  313,  314,  325,  323,  334,  320,  328,
      330,  316,  338,  339,  350,  348,  359,  301,  353,  355,
      295,  361,  367,  283,  368,  380,  276,  378,  387,  382,
      384,  252,  389,  391,  236,  395,  393,  399,  373,  402,

      408,  419,  232,  219,  199,  413,  415,  195,  423,  424,
      435,  433,  444,  187,  438,  440,  181,  446,  452,   99,
      453,  458,   74,  459,  465,  462,   51,  467,  468,  473,
       33,   27,  648,  488,  494,  499,  505,  510,  515,  518,
      521,    0
    } ;

static yyconst short int yy_def[343] =
    {   0,
      334,  334,  335,  335,  334,  334,  334,  334,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,

      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  336,  333,  333,  333,
      333,  333,  333,  333,  337,  333,  333,  333,  333,  333,
      333,  333,  338,  336,  339,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  337,  337,  333,
      333,  333,  333,  333,  333,  340,  338,  339,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  340,
      333,  333,  333,  333,  341,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  341,  333,  333,  333,  333,  333,  333,

      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  342,  333,  333,  333,  333,  333,  333,
      333,  333,  342,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,

      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,    0,  333,  333,  333,  333,  333,  333,  333,
      333,  333
    } ;

static yyconst short int yy_nxt[685] =
    {   0,
      333,   69,  117,   69,  117,  223,  120,   69,  120,   69,
       15,   15,   82,   83,   84,   87,   88,   89,   26,   83,
       84,   16,   16,   88,   89,  124,   26,  124,   11,   27,
       12,   13,   17,   17,   18,   18,   19,   28,  332,   12,
       13,   20,   21,   35,  332,   22,   23,   24,   40,   42,
       41,   43,   36,   29,   46,   38,  139,  140,  103,   29,
       83,   84,  329,  107,   19,   88,   89,  146,  147,   25,
       21,   12,   13,   22,   23,  103,  107,  103,  102,  106,
      137,  107,  119,  123,  144,  324,  119,  123,  133,  117,
      133,  117,  135,  136,  135,  136,  120,  137,  120,  143,

      124,  143,  124,  144,  138,  139,  140,  322,  145,  146,
      147,  133,  333,  133,  333,  135,  160,  135,  139,  140,
      146,  147,  165,  333,  165,  333,  333,  160,  333,  173,
      159,  173,  163,  165,  172,  165,  176,  181,  172,  181,
      176,  178,  179,  180,  182,  183,  182,  183,  184,  333,
      184,  186,  185,  186,  173,  187,  173,  191,  192,  193,
      179,  180,  188,  189,  190,  195,  181,  195,  181,  196,
      179,  180,  189,  190,  199,  200,  201,  182,  160,  182,
      183,  187,  183,  189,  190,  202,  203,  204,  205,  206,
      207,  184,  319,  184,  192,  193,  200,  201,  315,  208,

      209,  210,  213,  198,  192,  193,  310,  215,  200,  201,
      306,  215,  203,  204,  203,  204,  206,  207,  206,  207,
      209,  210,  209,  210,  211,  222,  213,  222,  220,  212,
      304,  216,  220,  221,  224,  226,  224,  221,  225,  226,
      217,  218,  219,  304,  227,  228,  229,  298,  227,  228,
      229,  230,  232,  230,  232,  231,  233,  222,  238,  222,
      238,  213,  239,  297,  233,  234,  235,  236,  240,  242,
      240,  242,  241,  243,  244,  249,  244,  249,  245,  235,
      236,  247,  247,  235,  236,  246,  250,  288,  250,  248,
      251,  286,  249,  248,  249,  247,  253,  254,  251,  256,

      252,  253,  254,  253,  254,  256,  283,  259,  256,  259,
      255,  260,  279,  260,  257,  262,  263,  264,  257,  263,
      264,  266,  266,  263,  264,  265,  268,  274,  268,  267,
      269,  270,  269,  267,  270,  268,  266,  268,  265,  270,
      272,  273,  260,  271,  272,  273,  275,  275,  272,  273,
      274,  277,  261,  277,  276,  278,  258,  278,  276,  279,
      277,  275,  277,  255,  279,  281,  282,  284,  280,  281,
      282,  281,  282,  284,  302,  287,  302,  287,  283,  288,
      251,  289,  285,  289,  284,  290,  285,  245,  289,  288,
      289,  294,  295,  296,  292,  293,  291,  292,  293,  292,

      293,  295,  296,  299,  297,  295,  296,  299,  300,  303,
      298,  303,  300,  304,  301,  305,  245,  305,  301,  306,
      302,  299,  302,  243,  306,  308,  309,  243,  307,  308,
      309,  311,  311,  308,  309,  310,  313,  241,  313,  312,
      314,  241,  314,  312,  315,  313,  311,  313,  239,  315,
      317,  318,  320,  316,  317,  318,  317,  318,  320,  325,
      323,  325,  323,  319,  324,  320,  325,  321,  325,  239,
      324,  321,  327,  328,  326,  327,  328,  327,  328,  329,
      331,  246,  331,  330,  332,  233,  231,  330,   10,   10,
       10,   10,   10,   10,   14,   14,   14,   14,   14,   14,

      134,  231,  134,  225,  134,  148,  148,  225,  148,  148,
      148,  157,  237,  157,  219,  157,  158,  218,  158,  217,
      158,  170,  170,  170,  194,  216,  194,  214,  196,  196,
      212,  211,  187,  198,  197,  177,  175,  174,  171,  169,
      168,  167,  166,  164,  149,  149,  163,  144,  162,  161,
      159,  137,  156,  155,  154,  153,  152,  151,  150,  149,
      142,  141,  132,  131,  130,  129,  128,  127,  126,  125,
      122,  121,  118,  116,  115,  114,  113,  112,  111,  110,
      109,  108,  106,  105,  104,  102,  101,  100,   99,   98,
       97,   96,   95,   94,   93,   92,   91,   90,   86,   85,

       81,   80,   79,   78,   77,   76,   75,   74,   73,   72,
       71,   70,   68,   67,   66,   65,   64,   63,   62,   61,
       60,   59,   58,   57,   56,   55,   54,   53,   52,   51,
       50,   49,   48,   47,   46,   45,   44,   39,   38,   37,
       34,   33,   32,   31,   30,   29,  333,    9,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333
    } ;

static yyconst short int yy_chk[685] =
    {   0,
        0,   53,  100,   53,  100,  342,  103,   69,  103,   69,
        3,    4,   66,   66,   66,   69,   69,   69,    7,   82,
       82,    3,    4,   87,   87,  107,    8,  107,    2,    7,
        2,    2,    3,    4,    3,    4,    5,    8,  332,    8,
        8,    5,    5,   18,  331,    5,    5,    6,   22,   23,
       22,   23,   18,   25,   28,   25,  138,  138,   84,   28,
       84,   84,  327,   89,    6,   89,   89,  145,  145,    6,
        6,    6,    6,    6,    6,  102,  106,  137,  102,  106,
      137,  144,  102,  106,  144,  323,  102,  106,  116,  117,
      116,  117,  118,  119,  118,  119,  120,  119,  120,  123,

      124,  123,  124,  123,  120,  120,  120,  320,  124,  124,
      124,  133,  134,  133,  134,  135,  140,  135,  140,  140,
      147,  147,  151,  157,  151,  157,  158,  159,  158,  160,
      159,  160,  163,  165,  159,  165,  163,  166,  159,  166,
      163,  165,  165,  165,  167,  168,  167,  168,  169,  170,
      169,  172,  170,  172,  173,  172,  173,  174,  174,  174,
      178,  178,  173,  173,  173,  176,  181,  176,  181,  176,
      180,  180,  188,  188,  181,  181,  181,  182,  187,  182,
      183,  187,  183,  190,  190,  182,  182,  182,  183,  183,
      183,  184,  317,  184,  191,  191,  199,  199,  314,  184,

      184,  184,  193,  198,  193,  193,  308,  198,  201,  201,
      305,  198,  202,  202,  204,  204,  205,  205,  207,  207,
      208,  208,  210,  210,  211,  213,  212,  213,  211,  212,
      304,  216,  211,  212,  215,  216,  215,  212,  215,  216,
      217,  218,  219,  303,  217,  218,  219,  295,  217,  218,
      219,  220,  221,  220,  221,  220,  221,  222,  226,  222,
      226,  233,  226,  292,  233,  222,  222,  222,  227,  228,
      227,  228,  227,  228,  229,  247,  229,  247,  229,  234,
      234,  236,  246,  236,  236,  246,  248,  287,  248,  246,
      248,  284,  249,  246,  249,  251,  252,  252,  251,  254,

      249,  249,  249,  254,  254,  255,  281,  257,  260,  257,
      255,  257,  278,  260,  255,  261,  261,  261,  255,  262,
      262,  264,  265,  264,  264,  265,  266,  272,  266,  265,
      267,  269,  267,  265,  267,  268,  270,  268,  263,  270,
      271,  271,  259,  268,  268,  268,  273,  274,  273,  273,
      274,  275,  258,  275,  274,  276,  256,  276,  274,  276,
      277,  279,  277,  253,  279,  280,  280,  282,  277,  277,
      277,  282,  282,  283,  299,  285,  299,  285,  283,  285,
      250,  286,  283,  286,  288,  286,  283,  245,  289,  288,
      289,  290,  290,  290,  291,  291,  289,  289,  289,  293,

      293,  294,  294,  296,  297,  296,  296,  298,  297,  300,
      298,  300,  297,  300,  298,  301,  244,  301,  298,  301,
      302,  306,  302,  243,  306,  307,  307,  242,  302,  302,
      302,  309,  310,  309,  309,  310,  311,  241,  311,  310,
      312,  240,  312,  310,  312,  313,  315,  313,  239,  315,
      316,  316,  318,  313,  313,  313,  318,  318,  319,  322,
      321,  322,  321,  319,  321,  324,  325,  319,  325,  238,
      324,  319,  326,  326,  325,  325,  325,  328,  328,  329,
      330,  235,  330,  329,  330,  232,  231,  329,  334,  334,
      334,  334,  334,  334,  335,  335,  335,  335,  335,  335,

      336,  230,  336,  225,  336,  337,  337,  224,  337,  337,
      337,  338,  223,  338,  209,  338,  339,  206,  339,  203,
      339,  340,  340,  340,  341,  200,  341,  197,  196,  195,
      192,  189,  186,  179,  177,  164,  162,  161,  156,  155,
      154,  153,  152,  150,  149,  148,  146,  143,  142,  141,
      139,  136,  132,  131,  130,  129,  128,  127,  126,  125,
      122,  121,  115,  114,  113,  112,  111,  110,  109,  108,
      105,  104,  101,   99,   97,   96,   95,   94,   93,   92,
       91,   90,   88,   86,   85,   83,   81,   80,   79,   78,
       77,   76,   75,   74,   73,   72,   71,   70,   68,   67,

       65,   64,   63,   62,   61,   60,   59,   58,   57,   56,
       55,   54,   52,   51,   50,   49,   48,   47,   46,   45,
       43,   42,   41,   40,   39,   38,   37,   36,   35,   34,
       33,   31,   30,   29,   27,   26,   24,   21,   20,   19,
       17,   16,   15,   13,   12,   11,    9,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cvtmod.l"
#define INITIAL 0
#line 2 "cvtmod.l"
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <math.h>
#include <assert.h>
	 
#define FALSE	0
#define TRUE	!FALSE

#define PCOUNT	1024		/* max polysets */
#define NUM_SHADERS	128	/* max shaders (textures) per pset */

void init_pset( char * );
void end_pset( void );
void add_vertex( char * );
void add_st( char * );
void add_tri( char * );
void add_tri2( char * );
void add_shader( char * );
void begin_shader( char * );
void begin_texture( char * );
void get_tex_name( char * );
void get_shd_name( char * );
void get_tex_type( char * );
void get_tex_parm( char *, float * );
void print_help( void );
int tricmp( const void *, const void * );
int tpcmp( const void *, const void * );

int nvtx = 0, nst = 0, ntri = 0, nsets = 0;
int ntex = 0, nshd = 0;

enum ttypes { TT_FILE, TT_PROJECTION, TT_SFRACTAL, TT_SKY };
enum stypes { ST_TEXTURE, ST_OTHER };

#ifdef JONHEY
char dir_name[128] = {0};

typedef struct wms_header 
{
	char reserved[16];
	int  w;
	int  h;
	int  small;
	int  large;
}	wms_header_t;
#endif

typedef struct _TEXTURE
{
	char	name[48];
	int		ttype;
	char	file[48];
	float	rotate;
	float	urepeat, vrepeat;
	float	uoffset, voffset;
	int		refs;			/* # of triangles that use it */
	int		index;			/* index after unref's textures are dropped */
} TEXTURE;

typedef struct _SHADER
{
	char	name[48];
	int		stype;
	char	texture[48];
} SHADER;

typedef struct _VERTEX
{
	float x,y,z;
} VERTEX;

typedef struct _ST
{
	float s,t;
} ST;

typedef struct _TRI
{
	int v1,v2,v3;
	int t1,t2,t3;
	int texture;
} TRI;

typedef struct _QUAD
{
	int v1,v2,v3,v4;
} QUAD;

typedef struct _POLYSET
{
	char	name[32];
	int		nvtx;
	int		ntri;
	int		nst;
	VERTEX	*pvtx;
	VERTEX	*pvn;
	ST		*pst;
	TRI		*ptri;
	int		shaders[NUM_SHADERS];
	int		nshaders;
} POLYSET;

#define MAX_VERTEX	(10 * 1024)
#define MAX_ST		(MAX_VERTEX * 3)
#define MAX_TRIS	(MAX_VERTEX * 4)
#define MAX_SHADER	(1024)
#define MAX_TEXTURE	(1024)

VERTEX	vtx[MAX_VERTEX];
ST		st[MAX_ST];
ST		new_st[MAX_ST];
TRI		tris[MAX_TRIS];
POLYSET psets[PCOUNT];
SHADER	shaders[MAX_SHADER];
TEXTURE	textures[MAX_TEXTURE];
TEXTURE *tptrs[MAX_TEXTURE];
VERTEX	*sort_vtx;
char	cur_tex[128];
char	cur_shd[128];
int		last_st[MAX_TRIS];
float	sfx = 1.0f;
float	sfy = 1.0f;
float	sfz = 1.0f;
int		debug_mode;
int		zsort_mode;
int		no_limbs;
int		no_textures;
int		net_anim;
int		reverse_tsort;			// reverse-sort by texture index
int		do_tsort;
#define PSET 1

#define STEX 2

#define SSHD 3

#line 763 "cvtmod.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 143 "cvtmod.l"


#line 920 "cvtmod.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 334 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 648 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 145 "cvtmod.l"
{ BEGIN PSET; init_pset( yytext ); };
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 146 "cvtmod.l"
{ BEGIN 0; end_pset(); };
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 147 "cvtmod.l"
add_tri( yytext );
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 148 "cvtmod.l"
add_tri2( yytext );
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 149 "cvtmod.l"
add_vertex( yytext );
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 150 "cvtmod.l"
add_st( yytext );
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 151 "cvtmod.l"
add_shader( yytext );
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 152 "cvtmod.l"
;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 154 "cvtmod.l"
{begin_texture( yytext );BEGIN STEX;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 155 "cvtmod.l"
{begin_shader( yytext );BEGIN SSHD;}
	YY_BREAK
case 11:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 156 "cvtmod.l"
get_tex_type( yytext );
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 157 "cvtmod.l"
get_tex_name( yytext );
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 158 "cvtmod.l"
get_tex_parm( yytext, &textures[ntex].rotate );
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 159 "cvtmod.l"
get_tex_parm( yytext, &textures[ntex].urepeat );
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 160 "cvtmod.l"
get_tex_parm( yytext, &textures[ntex].vrepeat );
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 161 "cvtmod.l"
get_tex_parm( yytext, &textures[ntex].uoffset );
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 162 "cvtmod.l"
get_tex_parm( yytext, &textures[ntex].voffset );
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 163 "cvtmod.l"
{ntex++;BEGIN 0;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 164 "cvtmod.l"
{get_shd_name( NULL );BEGIN 0;}
	YY_BREAK
case 20:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 165 "cvtmod.l"
{get_shd_name( yytext );BEGIN 0;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 166 "cvtmod.l"
{get_shd_name( NULL );BEGIN 0;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 168 "cvtmod.l"
;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 170 "cvtmod.l"
ECHO;
	YY_BREAK
#line 1125 "cvtmod.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PSET):
case YY_STATE_EOF(STEX):
case YY_STATE_EOF(SSHD):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 334 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 334 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 333);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 170 "cvtmod.l"


typedef enum { PS_NONE, PS_NAME, PS_SCALE, PS_SCALEX, PS_SCALEY,
	PS_SCALEZ, PS_APPEND, PS_MAP, PS_MAPW, PS_MAPH, PS_NETANIM } pstate;

/**********************************************************************/
int main( int argc, char *args[] )
{
	int i, j, k, m, n;
	int cf_square = FALSE;
	int cf_1x2 = FALSE;
	int cf_w = 0;
	int cf_h = 0;
#ifdef JONHEY
	int ar = 0;
	float sf;
	float tf;
#endif
	pstate pmode = PS_NONE;
	POLYSET *cp;
	char empty_string[] = "";
	char *np = NULL, *papp = empty_string, *nan = NULL;

#ifdef JONHEY
	float max_x,max_y,max_z,min_x,min_y,min_z;
	float vx,vy,vz;
#endif


	/* parse command flags */
	debug_mode = FALSE;
	zsort_mode = FALSE;
	no_limbs = FALSE;
	no_textures = FALSE;
	net_anim = FALSE;
	reverse_tsort = FALSE;
	do_tsort = TRUE;

	for( i = 1; i < argc; i++ )
	{
		switch( args[i][0] )
		{
			case '-':
				switch( args[i][1] )
				{
					case 'a':	/* append string to pset names */
						pmode = PS_APPEND;
						break;
					case 'd':	/* debug mode */
						debug_mode = TRUE;
						break;
					case 'f':	/* scale factor */
						switch( args[i][2] )
						{
							case '\0':
								pmode = PS_SCALE;
								break;
							case 'x':
								pmode = PS_SCALEX;
								break;
							case 'y':
								pmode = PS_SCALEY;
								break;
							case 'z':
								pmode = PS_SCALEZ;
								break;
							default:
								fprintf(stderr,"WARNING: Unrecognized command "
										"line option: %s\n", args[i] );
								break;
						}
						break;
					case 'h':	/* help */
						print_help();
						exit( 1 );
						break;
				#ifdef JONHEY
					case 'i':
						strcpy(dir_name,&args[i][2]);
						break;
				#endif
					case 'l':	/* no limb list */
						no_limbs = TRUE;
						break;
					case 'm':	/* scale factor */
						if (cf_square || cf_1x2)
						{
							fprintf(stderr,"WARNING: %s will be overridden "
									"by a previous option\n", args[i] );
						}
						switch( args[i][2] )
						{
							case '\0':
								pmode = PS_MAP;
								break;
							case 'w':
								pmode = PS_MAPW;
								break;
							case 'h':
								pmode = PS_MAPH;
								break;
							default:
								fprintf(stderr,"WARNING: Unrecognized command "
										"line option: %s\n", args[i] );
								break;
						}
						break;
					case 'n':	/* name */
						pmode = PS_NAME;
						break;
					case 'q':	/* no texture sort */
						do_tsort = FALSE;
						break;
					case 'r':	/* reverse texture sort */
						reverse_tsort = TRUE;
						break;
					case 's':	/* assume square textures */
						cf_square = TRUE;
						break;
					case 't':	/* no texture list */
						no_textures = TRUE;
						break;
					case 'v':	/* just output the vertex list */
						net_anim = TRUE;
						pmode = PS_NETANIM;
						break;
					case 'x':	/* assume 2x1 textures */
						if (cf_square)
						{
							fprintf(stderr,"WARNING: %s will be overridden "
									"by a previous option\n", args[i] );
						}
						cf_1x2 = TRUE;
						break;
					case 'z':	/* z-sort triangles */
						zsort_mode = TRUE;
						break;
					default:
						fprintf(stderr,"WARNING: Unrecognized command li"
								"ne option: %s\n", args[i] );
						break;
				}
				break;
			default:
				switch( pmode )
				{
					case PS_NETANIM:
						nan = args[i];
						break;
					case PS_NAME:
						np = args[i];
						break;
					case PS_SCALE:
						sfx = sfy = sfz = atof( args[i] );
						break;
					case PS_SCALEX:
						sfx = atof( args[i] );
						break;
					case PS_SCALEY:
						sfy = atof( args[i] );
						break;
					case PS_SCALEZ:
						sfz = atof( args[i] );
						break;
					case PS_APPEND:
						papp = args[i];
						break;
					case PS_MAP:
						cf_w = cf_h = atoi( args[i] );
						break;
					case PS_MAPW:
						cf_w = atoi( args[i] );
						break;
					case PS_MAPH:
						cf_h = atoi( args[i] );
						break;
					default:
						break;
				}
				break;
		}
	}


#ifdef JONHEY
	dir_name[0] = '\\';
	dir_name[1] = 'v';
	dir_name[2] = 'i';
	dir_name[3] = 'd';
	dir_name[4] = 'e';
	dir_name[5] = 'o';
	dir_name[6] = '\\';
	dir_name[7] = 'n';
	dir_name[8] = 'b';
	dir_name[9] = 'a';
	dir_name[10] = '\\';
	dir_name[11] = 'i';
	dir_name[12] = 'm';
	dir_name[13] = 'g';
	dir_name[14] = '3';
	dir_name[15] = 'd';
#endif


	/* read data */
	yylex();

	/* texture coverage check */
	for( i = 0; i < nsets; i++ )
	{
		cp = psets + i;

		for( j = 0; j < cp->ntri; j++ )
		{
			int prev_tex = -1;

			if( cp->ptri[j].texture != -1 )
				prev_tex = psets[i].shaders[cp->ptri[j].texture];

			if( prev_tex == -1 )
				printf( "Problem in polyset %s.\n", cp->name );

			assert( prev_tex != -1 );

			textures[prev_tex].refs++;
		}
	}

	/* make an array of pointers to the texture list, then sort it by name */
	for( j = 0; j < ntex; j++ )
	{
		tptrs[j] = textures + j;
	}
	qsort( tptrs, ntex, sizeof( TEXTURE * ), tpcmp );

	/* assign texture indexes */
	for( j = k = 0; j < ntex; j++ )
	{
		if( tptrs[j]->refs )
			tptrs[j]->index = k++;
		else
			tptrs[j]->index = -1;
	}


	for( i = 0; i < nsets; i++ )
	{
		cp = psets + i;
		printf( "VERTEX %s%s_vtx[] =\n{\n", psets[i].name, papp );

		for( j = 0; j < cp->nvtx; j++ )
		{
			printf( "\t{%ff,%ff,%ff}",
					cp->pvtx[j].x,
					cp->pvtx[j].y,
					cp->pvtx[j].z );
			if( j < cp->nvtx - 1 )
				printf( ",\n" );
		}
		
		printf( "\n};\n\n" );
	}






#ifdef JONHEY

	for( i = 0; i < nsets; i++ )
	{
		cp = psets + i;
		printf( "VERTEX %s%s_bbox[] =\n{\n", psets[i].name, papp );

		max_x = cp->pvtx[0].x;
		max_y = cp->pvtx[0].y;
		max_z = cp->pvtx[0].z;
		min_x = cp->pvtx[0].x;
		min_y = cp->pvtx[0].y;
		min_z = cp->pvtx[0].z;
			
		for( j = 0; j < cp->nvtx; j++ )
			{

			vx = cp->pvtx[j].x;
			vy = cp->pvtx[j].y;
			vz = cp->pvtx[j].z;

			if (vx < min_x)
				min_x = vx;

			if (vy < min_y)
				min_y = vy;

			if (vz < min_z)
				min_z = vz;

			if (vx > max_x)
				max_x = vx;

			if (vy > max_y)
				max_y = vy;

			if (vz > max_z)
				max_z = vz;

			}
	
			printf("\t{%ff,%ff,%ff},\n",min_x,min_y,min_z);
			printf("\t{%ff,%ff,%ff},\n",min_x,min_y,max_z);
			printf("\t{%ff,%ff,%ff},\n",min_x,max_y,min_z);
			printf("\t{%ff,%ff,%ff},\n",min_x,max_y,max_z);
			printf("\t{%ff,%ff,%ff},\n",max_x,min_y,min_z);
			printf("\t{%ff,%ff,%ff},\n",max_x,min_y,max_z);
			printf("\t{%ff,%ff,%ff},\n",max_x,max_y,min_z);
			printf("\t{%ff,%ff,%ff}\n};\n\n",max_x,max_y,max_z);

	}

#endif


	if(net_anim)
	{
		printf( "VERTEX *%s_verts[] =\n{\n", np ? np : "xxx" );
		for( i = 0; i < nsets; i++ )
			printf( "\t%s%s_vtx,\n", psets[i].name, papp );

//printf( "\t&limb_%s%s,\n", psets[i].name, papp );

		printf( "\tNULL\n};\n\n" );

#ifdef JONHEY
		printf( "VERTEX *%s_bbox[] =\n{\n", np ? np : "xxx" );
		for( i = 0; i < nsets; i++ )
			{
			if (psets[i].nvtx > 8)
				{
				printf( "\t%s%s_bbox,\n", psets[i].name, papp );
				}
			else
				{
				printf("\tNULL,\t/* bounding box */\n" );
				}
			}
		printf( "\tNULL\n};\n\n" );
#endif

	}

 if(!net_anim)
 {
	/* mangle data */

	for( i = 0; i < nsets; i++ )
	{
		cp = psets + i;

		/* sort the triangles by texture index and mean z */
		sort_vtx = cp->pvtx;
		qsort( cp->ptri, cp->ntri, sizeof( TRI ), tricmp );

		/* create unique u-v pairs for each instance of a vertex */
		for( j = 0; j < cp->ntri; j++ )
		{
			TEXTURE *ptex = textures + cp->shaders[cp->ptri[j].texture];
	
		#ifdef JONHEY
			ar = get_aspect_ratio (ptex->file);

			sf = tf = 256.0f;
			switch( ar )
			{
				case 0:	/* 8W x 1H */
					tf = 32.0f;
					break;
				case 1:	/* 4W x 1H */
					tf = 64.0f;
					break;
				case 2:	/* 2W x 1H */
					tf = 128.0f;
					break;
				case 3:	/* 1W x 1H */
					break;
				case 4:	/* 1W x 2H */
					sf = 128.0f;
					break;
				case 5:	/* 1W x 4H */
					sf = 64.0f;
					break;
				case 6:	/* 1W x 8H */
					sf = 32.0f;
					break;
				default:
					fprintf(stderr,"unrecognized aspect ratio: %d\n\r",ar);
					exit (0);
			}	

			new_st[j*3].s = sf * cp->pst[cp->ptri[j].t1].s;
			new_st[j*3].t = tf * (1.0f - cp->pst[cp->ptri[j].t1].t);
			new_st[j*3+1].s = sf * cp->pst[cp->ptri[j].t2].s;
			new_st[j*3+1].t = tf * (1.0f - cp->pst[cp->ptri[j].t2].t);
			new_st[j*3+2].s = sf * cp->pst[cp->ptri[j].t3].s;
			new_st[j*3+2].t = tf * (1.0f - cp->pst[cp->ptri[j].t3].t);

		#else

			new_st[j*3].s = cp->pst[cp->ptri[j].t1].s;
			new_st[j*3].t = cp->pst[cp->ptri[j].t1].t;
			new_st[j*3+1].s = cp->pst[cp->ptri[j].t2].s;
			new_st[j*3+1].t = cp->pst[cp->ptri[j].t2].t;
			new_st[j*3+2].s = cp->pst[cp->ptri[j].t3].s;
			new_st[j*3+2].t = cp->pst[cp->ptri[j].t3].t;

		#endif			

			new_st[j*3].s *= ptex->urepeat;
			new_st[j*3].t *= ptex->vrepeat;
			new_st[j*3+1].s *= ptex->urepeat;
			new_st[j*3+1].t *= ptex->vrepeat;
			new_st[j*3+2].s *= ptex->urepeat;
			new_st[j*3+2].t *= ptex->vrepeat;

			new_st[j*3].s += ptex->uoffset;
			new_st[j*3].t += ptex->voffset;
			new_st[j*3+1].s += ptex->uoffset;
			new_st[j*3+1].t += ptex->voffset;
			new_st[j*3+2].s += ptex->uoffset;
			new_st[j*3+2].t += ptex->voffset;

			cp->ptri[j].t1 = j*3;
			cp->ptri[j].t2 = j*3+1;
			cp->ptri[j].t3 = j*3+2;
		}
		cp->nst = j * 3;


		// crunch the list, eliminating duplicates
		// A: Start at the front of the list and scan forward for matches.
		// When a match is found, go through the triangle list and change
		// any references to the later match to point to the lower match,
		// then shuffle the remaining list entries down a notch to remove
		// the match, and keep going.
		for( k = 0; k < cp->nst; k++ )
		{
			for( m = k+1; m < cp->nst; m++ )
			{

				if(( new_st[k].s == new_st[m].s ) &&
					(new_st[k].t == new_st[m].t ))
				{
					/* update the triangle list */
					for( n = 0; n < cp->ntri; n++ )
					{
						if(cp->ptri[n].t1 == m)
							cp->ptri[n].t1 = k;
						if(cp->ptri[n].t2 == m)
							cp->ptri[n].t2 = k;
						if(cp->ptri[n].t3 == m)
							cp->ptri[n].t3 = k;
						if(cp->ptri[n].t1 > m)
							cp->ptri[n].t1 -= 1;
						if(cp->ptri[n].t2 > m)
							cp->ptri[n].t2 -= 1;
						if(cp->ptri[n].t3 > m)
							cp->ptri[n].t3 -= 1;
					}

					/* shuffle the remaning ST entries each down a notch */
					for( n = m+1; n < cp->nst; n++ )
					{
						new_st[n-1].s = new_st[n].s;
						new_st[n-1].t = new_st[n].t;
					}
	
					cp->nst -= 1;
					m -= 1;
				}
			}
		}

		/* check to see if we will collide with the 255 sentinel */
		if (cp->nst > 254) {
			for (n = cp->nst; n >= 255; n--) {
				new_st[n + 1].s = new_st[n].s;
				new_st[n + 1].t = new_st[n].t;
			}
			new_st[255].s = 0;
			new_st[255].t = 0;
			cp->nst++;

			/* update the triangle list */
			for (n = 0; n < cp->ntri; n++) {
				if(cp->ptri[n].t1 >= 255)
					cp->ptri[n].t1++;
				if(cp->ptri[n].t2 >= 255)
					cp->ptri[n].t2++;
				if(cp->ptri[n].t3 >= 255)
					cp->ptri[n].t3++;
			}
		}			

		// Assign texture codes.  A nonnegative integer is a texture
		// index, and all three vertex uv pairs will be pointers.  a
		// negative integer means that we use the same texture as the
		// previous triangle.  Value will be -1, minus the number of
		// uv indices that are -1.  Just set it to -1 for now, and
		// let the rotate loop subtract off the number of -1s among
		// the uv indices.
		for( j = cp->ntri -1; j; j-- )
		{
			if( cp->ptri[j-1].texture == cp->ptri[j].texture )
				cp->ptri[j].texture = -1;
		}

		// walk the triangle list.  Any time a vertex is matched with
		// the same ST index as the last time it was referenced, change
		// the index to a 255.  This signals the geometry code to skip
		// the vtx->oow * st multiplies.  DONT, however, do this in
		// triangles that begin a new texture.  This shouldn't ever
		// happen anyway, though.
		for( j = 0; j < cp->ntri*3; j++ )
			last_st[j] = 255;
		for( j = 0; j < cp->ntri; j++ )
		{
			// check for new texture
			if( cp->ptri[j].texture >= 0 )
			{
				last_st[cp->ptri[j].v1] = cp->ptri[j].t1;
				last_st[cp->ptri[j].v2] = cp->ptri[j].t2;
				last_st[cp->ptri[j].v3] = cp->ptri[j].t3;
				continue;
			}

#ifndef JONHEY	
			if( cp->ptri[j].t1 == last_st[cp->ptri[j].v1] )
				cp->ptri[j].t1 = 255;
			else
#endif
				last_st[cp->ptri[j].v1] = cp->ptri[j].t1;

#ifndef JONHEY	
			if( cp->ptri[j].t2 == last_st[cp->ptri[j].v2] )
				cp->ptri[j].t2 = 255;
			else
#endif
				last_st[cp->ptri[j].v2] = cp->ptri[j].t2;

#ifndef JONHEY	
			if( cp->ptri[j].t3 == last_st[cp->ptri[j].v3] )
				cp->ptri[j].t3 = 255;
			else
#endif
				last_st[cp->ptri[j].v3] = cp->ptri[j].t3;
		}

		// Now go through the triangle list and rotate vs and ts such
		// that all the 255's in the ts are packed to the right.
		for( j = 0; j < cp->ntri; j++ )
		{
			k = 0;

			if( cp->ptri[j].t3 == 255 )
			{
				k |= 0x01;
				cp->ptri[j].texture--;
			}
			if( cp->ptri[j].t2 == 255 )
			{
				k |= 0x02;
				cp->ptri[j].texture--;
			}
			if( cp->ptri[j].t1 == 255 )
			{
				k |= 0x04;
				cp->ptri[j].texture--;
			}

			if(( k == 2 ) || ( k == 6 ))
			{
				// rotate right
				m = cp->ptri[j].v1;
				cp->ptri[j].v1 = cp->ptri[j].v3;
				cp->ptri[j].v3 = cp->ptri[j].v2;
				cp->ptri[j].v2 = m;
				m = cp->ptri[j].t1;
				cp->ptri[j].t1 = cp->ptri[j].t3;
				cp->ptri[j].t3 = cp->ptri[j].t2;
				cp->ptri[j].t2 = m;

			}

			if(( k == 4 ) || ( k == 5 ))
			{
				// rotate left
				m = cp->ptri[j].v3;
				cp->ptri[j].v3 = cp->ptri[j].v1;
				cp->ptri[j].v1 = cp->ptri[j].v2;
				cp->ptri[j].v2 = m;
				m = cp->ptri[j].t3;
				cp->ptri[j].t3 = cp->ptri[j].t1;
				cp->ptri[j].t1 = cp->ptri[j].t2;
				cp->ptri[j].t2 = m;
			}
		}

#if 0
		printf( "VERTEX %s%s_vn[] =\n{\n", psets[i].name, papp );
		for( j = 0; j < cp->nvtx; j++ )
		{
			printf( "\t{%ff,%ff,%ff}",
					cp->pvn[j].x,
					cp->pvn[j].y,
					cp->pvn[j].z );
			if( j < cp->nvtx - 1 )
				printf( ",\n" );
		}
#endif

		printf( "TRI %s%s_tris[] =\n{\n", psets[i].name, papp );
		for( j = 0; j < cp->ntri; j++ )
		{

	#ifndef JONHEY											 
			printf( "\t{%d,%d,%d, %d,%d,%d, %d},\n",
					3*cp->ptri[j].v1,
					3*cp->ptri[j].v2,
					3*cp->ptri[j].v3,
					cp->ptri[j].t1,
					cp->ptri[j].t2,
					cp->ptri[j].t3,
					cp->ptri[j].texture < 0 ? (cp->ptri[j].texture * 4) :
					(4*textures[psets[i].shaders[cp->ptri[j].texture]].index));

	#else

			printf( "\t{%d,%d,%d, %d,%d,%d, %d},\n",
					cp->ptri[j].v1,
					cp->ptri[j].v2,
					cp->ptri[j].v3,
					cp->ptri[j].t1,
					cp->ptri[j].t2,
					cp->ptri[j].t3,
					cp->ptri[j].texture < 0 ? (cp->ptri[j].texture * 4) :
					(4*textures[psets[i].shaders[cp->ptri[j].texture]].index));
	
	#endif

		}
		printf( "\t{0, 0, 0, 0, 0, 0, -20}\n};\n\n" );

		printf( "ST %s%s_st[] =\n{\n", psets[i].name, papp );
		for( j = 0; j < cp->nst; j++ )
		{

	#ifndef JONHEY											 
			float	sf,tf;

			if (cf_square)
			{
				sf = 256.0f;	tf = 256.0f;
			}
			else if (cf_1x2)
			{
				sf = 256.0f;	tf = 128.0f;
			}
			else
			{
				sf = pow2(cf_w);		tf = pow2(cf_h);
			}


			printf( "\t{%ff,%ff}",
					sf * new_st[j].s,
					tf * (1.0f - new_st[j].t ));
			if( j < cp->nst - 1 )
				printf( ",\n" );
	#else

			printf( "\t{%ff,%ff}",
					new_st[j].s,
					new_st[j].t);

			if( j < cp->nst - 1 )
				printf( ",\n" );
  	#endif
		}

		printf( "\n};\n\n" );


	}


	for( i = 0; i < nsets; i++ )
	{
		printf("LIMB limb_%s%s = \n{\n", psets[i].name, papp);
		printf("\t%d,\t\t\t\t/* vertex count */\n", psets[i].nvtx);
		printf("\t%d,\t\t\t\t/* triangle count */\n", psets[i].ntri);
#if 0
		printf("\t%s%s_vn,\t/* vertex normals */\n", psets[i].name, papp);
#else
		printf("\tNULL,\t/* vertex normals */\n" );
#endif
		printf("\t%s%s_vtx,\t/* vertices */\n", psets[i].name, papp);
		printf("\t%s%s_st,\t/* texture coordinates */\n", psets[i].name, papp);
		printf("\t%s%s_tris,\t/* triangles */\n", psets[i].name, papp);
#ifdef JONHEY
		if (psets[i].nvtx > 8)
			{
			printf("\t%s%s_bbox,\t/* bounding box */\n", psets[i].name, papp);
			}
		else
			{
			printf("\tNULL,\t/* bounding box */\n" );
			}
#endif
		printf("};\n\n");
	}

	if (!no_limbs)
	{
		printf( "LIMB *%s_limbs[] =\n{\n", np ? np : "xxx" );
		for( i = 0; i < nsets; i++ )
			printf( "\t&limb_%s%s,\n", psets[i].name, papp );
		printf( "\tNULL\n};\n\n" );
	}

	if (!no_textures)
	{
		printf( "char *%s_textures[] =\n{\n", np ? np : "xxx" );
		for( i = 0; i < ntex; i++ )
		{
			if( tptrs[i]->index != -1 )
			{
				if( tptrs[i]->file[strlen(tptrs[i]->file)-4] == '.' )
				{
					tptrs[i]->file[strlen(tptrs[i]->file)-3] = 'w';
					tptrs[i]->file[strlen(tptrs[i]->file)-2] = 'm';
					tptrs[i]->file[strlen(tptrs[i]->file)-1] = 's';
				}
				printf( "\t\"%s\",\n", tptrs[i]->file );
			}
		}
		printf( "\tNULL\n};\n" );
	}
 }
	return 0;
}


/**********************************************************************/
void init_pset( char *text )
{
	int i;

	sscanf( text, "polyset %s (", psets[nsets].name );
	nvtx = 0;
	ntri = 0;
	nst = 0;
	for( i = 0; i < NUM_SHADERS; i++ )
		psets[nsets].shaders[i] = 0;
	psets[nsets].nshaders = 0;

	if( debug_mode )
	{
		printf( "init_pset( %s )\n", psets[nsets].name );
	}
}


/**********************************************************************/
void end_pset( void )
{
	VERTEX	*pvtx, *vn;
	TRI		*ptri;
	ST		*pst;
	int		i;

	/* allocate space for vertex normals */
	vn = (VERTEX *)malloc( sizeof( VERTEX ) * nvtx );
	if (vn == NULL) {
		fprintf(stderr, "could not malloc vertex normal list\n");
		abort();
	}

	/* compute vertex normals */
	for( i = 0; i < nvtx; i++ )
	{
		vn[i].x = 0.0f;
		vn[i].y = 0.0f;
		vn[i].z = 0.0f;
	}

	for( i = 0; i < ntri; i++ )
	{
		VERTEX v12, v13, vsn;

		/* compute surface normal */
		v12.x = vtx[tris[i].v2].x - vtx[tris[i].v1].x;
		v12.y = vtx[tris[i].v2].y - vtx[tris[i].v1].y;
		v12.z = vtx[tris[i].v2].z - vtx[tris[i].v1].z;

		v13.x = vtx[tris[i].v3].x - vtx[tris[i].v1].x;
		v13.y = vtx[tris[i].v3].y - vtx[tris[i].v1].y;
		v13.z = vtx[tris[i].v3].z - vtx[tris[i].v1].z;

		vsn.x = v13.y * v12.z - v13.z * v12.y;
		vsn.y = v13.z * v12.x - v13.x * v12.z;
		vsn.z = v13.x * v12.y - v13.y * v12.x;

		/* add to component vertex normals */
		vn[tris[i].v1].x += vsn.x;
		vn[tris[i].v1].y += vsn.y;
		vn[tris[i].v1].z += vsn.z;

		vn[tris[i].v2].x += vsn.x;
		vn[tris[i].v2].y += vsn.y;
		vn[tris[i].v2].z += vsn.z;

		vn[tris[i].v3].x += vsn.x;
		vn[tris[i].v3].y += vsn.y;
		vn[tris[i].v3].z += vsn.z;
	}

	/* normalize vertex normals */
	for( i = 0; i < nvtx; i++ )
	{
		float magv;

		magv = (float)sqrt((double)(vn[i].x*vn[i].x+vn[i].y*vn[i].y+vn[i].z*vn[i].z));
		if (magv > 0.000001f) {
			vn[i].x /= magv;
			vn[i].y /= magv;
			vn[i].z /= magv;
		}
	}

	/* make a copy of the vertex scratch pad */
	pvtx = (VERTEX *)malloc( sizeof( VERTEX ) * nvtx );

	if( pvtx == NULL )
	{
		printf( "Error allocating space for vertex list.  Aborting.\n" );
		exit( 0 );
	}

	for( i = 0; i < nvtx; i++ )
	{
		pvtx[i].x = vtx[i].x;
		pvtx[i].y = vtx[i].y;
		pvtx[i].z = vtx[i].z;
	}


	/* make a copy of the triangle scratch pad */
	ptri = (TRI *)malloc( sizeof( TRI ) * ntri );

	if( ptri == NULL )
	{
		printf( "Error allocating space for triangle list.  Aborting.\n" );
		exit( 0 );
	}

	for( i = 0; i < ntri; i++ )
	{
		ptri[i].v1 = tris[i].v1;
		ptri[i].v2 = tris[i].v2;
		ptri[i].v3 = tris[i].v3;
		ptri[i].t1 = tris[i].t1;
		ptri[i].t2 = tris[i].t2;
		ptri[i].t3 = tris[i].t3;
		ptri[i].texture = tris[i].texture;
	}

	/* make a copy of the s&t scratch pad */
	pst = (ST *)malloc( sizeof( ST ) * nst );

	if( pst == NULL )
	{
		printf( "Error allocating space for s&t list.  Aborting.\n" );
		exit( 0 );
	}

	for( i = 0; i < nst; i++ )
	{
		pst[i].s = st[i].s;
		pst[i].t = st[i].t;
	}

	psets[nsets].pvtx = pvtx;
	psets[nsets].ptri = ptri;
	psets[nsets].pst = pst;
	psets[nsets].nvtx = nvtx;
	psets[nsets].ntri = ntri;
	psets[nsets].nst = nst;
	psets[nsets].pvn = vn;

	if( debug_mode )
	{
		printf( "end_pset( %s )\n", psets[nsets].name );
		printf( " nvtx: %d ntri: %d\n", nvtx, ntri );
	}

	nsets++;
}


/**********************************************************************/
void add_vertex( char *text )
{
	float x,y,z;

	if( nvtx == MAX_VERTEX )
	{
		fprintf( stderr, "Error: Too many vertices.\n" );
		exit( 0 );
	}

	sscanf( text, "cv((%f, %f, %f", &x, &y, &z );
	vtx[nvtx].x = x * sfx;
	vtx[nvtx].y = y * sfy;
	vtx[nvtx].z = z * sfz;
	nvtx++;
}


/**********************************************************************/
void add_st( char *text )
{
	float s,t;

	if( nst == MAX_ST )
	{
		fprintf( stderr, "Error: Too many st pairs.\n" );
		exit( 0 );
	}

	sscanf( text, "st( %f, %f", &s, &t );
	st[nst].s = s;
	st[nst].t = t;
	nst++;
}


/**********************************************************************/
void add_tri( char *text )
{
	int	v1,v2,v3,t1,t2,t3,tex;

	if( ntri == MAX_TRIS )
	{
		fprintf( stderr, "Error: Too many triangles.\n" );
		exit( 0 );
	}

	sscanf( text, "polygon ((%d, %d, %d),(%d, %d, %d), %d",
			&v1, &v2, &v3, &t1, &t2, &t3, &tex );
	tris[ntri].v1 = v1;
	tris[ntri].v2 = v2;
	tris[ntri].v3 = v3;
	tris[ntri].t1 = t1;
	tris[ntri].t2 = t2;
	tris[ntri].t3 = t3;
	tris[ntri].texture = tex;
	ntri++;
}


/**********************************************************************/
void add_tri2( char *text )
{
	int	v1,v2,v3,t1,t2,t3,n1,n2,n3,tex;

	if( ntri == MAX_TRIS )
	{
		fprintf( stderr, "Error: Too many triangles.\n" );
		exit( 0 );
	}

	sscanf( text, "polygon ((%d, %d, %d),(%d, %d, %d), (%d, %d, %d), %d",
			&v1, &v2, &v3, &t1, &t2, &t3, &n1, &n2, &n3, &tex );
	tris[ntri].v1 = v1;
	tris[ntri].v2 = v2;
	tris[ntri].v3 = v3;
	tris[ntri].t1 = t1;
	tris[ntri].t2 = t2;
	tris[ntri].t3 = t3;
	tris[ntri].texture = tex;
	ntri++;
}


/**********************************************************************/
void add_shader( char *text )
{
	char *c;
	int i,j;

	/* extract the name */
	c = text+10;

	/* look up this shader */
	for( i = 0; (i < nshd) && (strcmp( c, shaders[i].name )); i++ );

	if( i == nshd )
	{
		fprintf( stderr, "Error: unmatched shader %s\n", c );
		exit( 0 );
	}

	/* found the shader.  now look up the color */
	if( shaders[i].stype == ST_TEXTURE )
	{
		for( j = 0; (j < ntex) && (strcmp( shaders[i].texture,
				textures[j].name )); j++ );

		if( j == ntex )
		{
			fprintf( stderr, "Error: shader %s has unmatched texture %s\n",
				shaders[i].name, shaders[i].texture );
			exit( 0 );
		}
		psets[nsets].shaders[psets[nsets].nshaders] = j;

		if( debug_mode )
		{
			printf( " ref shader: %s, uses texture %s\n", c, textures[j].name );
		}
	}
	else
	{
		psets[nsets].shaders[psets[nsets].nshaders] = -1;
	}

	psets[nsets].nshaders++;
}


/**********************************************************************/
int yywrap( void )
{
	return 1;
}

/**********************************************************************/
void begin_texture( char *text )
{
	if( strlen( text ) > 55 )
	{
		printf( "Error.  Texture %s name too long.\n", text+8 );
	}
	strcpy( cur_tex, text+8 );

	if( debug_mode )
	{
		printf( "Texture: \"%s\"\n", text+8 );
	}
}

/**********************************************************************/
void begin_shader( char *text )
{
	if( strlen( text ) > 54 )
	{
		printf( "Error.  Shader` %s name too long.\n", text+7 );
	}
	strcpy( cur_shd, text+7 );

	if( debug_mode )
	{
		printf( "Shader: \"%s\"\n", text+7 );
	}
}

/**********************************************************************/
void get_tex_name( char *text )
{
	char *c;

	/*	image = "/abc/def/ghi/filename.TIF",	*/
	/*	image = File#213,						*/

	/* trim off trailing commas or quotes */
	for( c = text + strlen( text ) - 1; (*c == ',') || (*c == '"' ); c-- )
		*c = '\0';

	/* now back up until we find either a frontslash or a whitespace char */
	for( ; (*c != ' ') && (*c != '\t') && (*c != '/'); c-- );

	strcpy( textures[ntex].name, cur_tex );
	strcpy( textures[ntex].file, c+1 );
	textures[ntex].refs = 0;
}

/**********************************************************************/
void get_shd_name( char *text )
{
	char *c;

	if( text )
	{
		/* find the beginning */
		for( c = text + strlen( text ) -1; *c != ' '; c-- );

		strcpy( shaders[nshd].texture, c+1 );
		shaders[nshd].stype = ST_TEXTURE;
	}
	else
	{
		shaders[nshd].stype = ST_OTHER;
	}

	strcpy( shaders[nshd].name, cur_shd );
	nshd++;
}

/**********************************************************************/
void get_tex_type( char *text )
{
	char *c;

	c = text+12;

	if( !strcmp( c, "Sky" ))
	{
		textures[ntex].ttype = TT_SKY;
		ntex++;
		BEGIN 0;
	}
	else if( !strcmp( c, "file" ))
	{
		textures[ntex].ttype = TT_FILE;
	}
	else if( !strcmp( c, "Projection" ))
	{
		textures[ntex].ttype = TT_PROJECTION;
	}
	else if( !strcmp( c, "sFractal" ))
	{
		textures[ntex].ttype = TT_SFRACTAL;
		ntex++;
		BEGIN 0;
	}
	else
	{
		fprintf( stderr, "Error!  Unknown texture type: %s\n", c );
		exit( 0 );
	}
}

/**********************************************************************/
void get_tex_parm( char *text, float *val )
{
	char *c;

	/* look for the first digit */
	c = text;
	while( !isdigit( *c ))
		c++;

	*val = atof( c );

	return;
}

/**********************************************************************/
void print_help( void )
{
	printf( "cvtmod [options] infile" );
}

/**********************************************************************/
// NOTE:
// For whatever reason, this doesn't seem to be working
// reliably.  The sort by texture indices is somehow fucked
// up, but I (JMS) dont have time to deal with it just now.
// Be aware that if you think you're getting bogus sorts,
// you're probably right.

int tricmp( const void *p1, const void *p2 )
{
	TRI		*t1, *t2;
	float	z1,z2;

	t1 = (TRI *)p1;
	t2 = (TRI *)p2;

	if( do_tsort )
	{
		if(( t1->texture - t2->texture ) || !zsort_mode )
			return(( t1->texture - t2->texture ) * (reverse_tsort ? -1 : 1));
	}

	z1 = sort_vtx[t1->v1].z + sort_vtx[t1->v2].z + sort_vtx[t1->v3].z;
	z2 = sort_vtx[t2->v1].z + sort_vtx[t2->v2].z + sort_vtx[t2->v3].z;

	return( z1 - z2 );
}

/**********************************************************************/
int tpcmp( const void *p1, const void *p2 )
{
	TEXTURE	**t1, **t2;

	t1 = (TEXTURE **)p1;
	t2 = (TEXTURE **)p2;

	return( strcmp( (*t1)->file, (*t2)->file ) );
}

/**********************************************************************/


#ifdef JONHEY
int get_aspect_ratio (char *name)
{
	char work_name[128];
	char file_spec[128];
	FILE *fp;
	char *tmp;
	int ar;
	wms_header_t wms_header;

	strcpy(work_name,name);
	tmp = strstr(work_name, ".TIF");
	if (!tmp)
	{
		tmp = strstr(work_name, ".tif");
		if (!tmp)
		{
			fprintf(stderr,"unrecognized texture extension: %s\n\r",name);
			return(3);
//			exit(0);
		}
	}
	strcpy(tmp,".wms");

	strcpy(file_spec,dir_name);

	tmp = strrchr(dir_name,'\\');
	if (tmp)
	{
		++tmp;
		if( isalnum(*tmp) )
		{
			strcat(dir_name,"\\");
		}
	}
	else
	{
	dir_name[0] = 0;
	}

	sprintf(file_spec,"%s%s",dir_name,work_name);


	if((fp=fopen(file_spec,"rb")) == (FILE *)0)
	{
		fprintf(stderr,"can't open file: %s\n\r",file_spec);
		exit(0);
	}

	fread(&wms_header,sizeof(wms_header_t),1,fp);
//	printf("wms.w %d %d %d %d\n",wms_header.w,wms_header.h,wms_header.small,wms_header.large);
	fread(&ar,sizeof(int),1,fp);
	fclose(fp);
//	printf("ar: %x\n",ar);
	
	return (ar);
}
#endif