3df2wms.o: 3df2wms.c /video/include/stdio.h \
 /video/include/sys/djtypes.h /video/include/string.h \
 /video/include/sys/movedata.h /video/include/ctype.h \
 /video/include/inlines/ctype.ha /video/include/inlines/ctype.hd \
 /video/include/dir.h /video/include/sys/stat.h \
 /video/include/sys/types.h /video/include/unistd.h \
 /video/tools/zlib/zlib.h /video/tools/zlib/zconf.h \
 /video/include/glide/glide.h /video/include/glide/3dfx.h \
 /video/include/glide/sst1vid.h /video/include/glide/glidesys.h \
 /video/include/glide/glideutl.h
