pdremove.o: pdremove.c c:/djgpp/include/libc/stubs.h \
 c:/djgpp/include/io.h c:/djgpp/include/sys/types.h \
 c:/djgpp/include/sys/djtypes.h c:/djgpp/include/stdio.h \
 c:/djgpp/include/libc/dosio.h c:/djgpp/include/go32.h \
 c:/djgpp/include/sys/movedata.h c:/djgpp/include/sys/segments.h \
 c:/djgpp/include/dpmi.h c:/djgpp/include/errno.h \
 c:/djgpp/include/dos.h c:/djgpp/include/pc.h \
 c:/djgpp/include/inlines/pc.h pd.h
