all:
	@$(MAKE) --no-print-directory -f nbarom.mak rebuild
	@$(MAKE) --no-print-directory -f nflrom.mak rebuild
	@$(MAKE) --no-print-directory -f b99rom.mak rebuild
	@$(MAKE) --no-print-directory -f srrom.mak rebuild
	@$(MAKE) --no-print-directory -f carnrom.mak rebuild

vegas:
	@$(MAKE) --no-print-directory -f vegasrom.mak rebuild

clobber:
	@$(MAKE) --no-print-directory -f nbarom.mak clobber
	@$(MAKE) --no-print-directory -f nflrom.mak clobber
	@$(MAKE) --no-print-directory -f b99rom.mak clobber
	@$(MAKE) --no-print-directory -f srrom.mak clobber
	@$(MAKE) --no-print-directory -f carnrom.mak clobber
	@$(MAKE) --no-print-directory -f vegasrom.mak clobber

clean:
	@$(MAKE) --no-print-directory -f nbarom.mak clean
	@$(MAKE) --no-print-directory -f nflrom.mak clean
	@$(MAKE) --no-print-directory -f b99rom.mak clean
	@$(MAKE) --no-print-directory -f srrom.mak clean
	@$(MAKE) --no-print-directory -f carnrom.mak clean
	@$(MAKE) --no-print-directory -f vegasrom.mak clean

rebuild:
	@$(MAKE) --no-print-directory -f nbarom.mak rebuild
	@$(MAKE) --no-print-directory -f nflrom.mak rebuild
	@$(MAKE) --no-print-directory -f b99rom.mak rebuild
	@$(MAKE) --no-print-directory -f srrom.mak rebuild
	@$(MAKE) --no-print-directory -f carnrom.mak rebuild
	@$(MAKE) --no-print-directory -f vegasrom.mak rebuild
