all:
	@$(MAKE) --no-print-directory -f nbabios.mak rebuild
	@$(MAKE) --no-print-directory -f nbatest.mak rebuild
	@$(MAKE) --no-print-directory -f nflbios.mak rebuild
	@$(MAKE) --no-print-directory -f nfltest.mak rebuild
	@$(MAKE) --no-print-directory -f b99bios.mak rebuild
	@$(MAKE) --no-print-directory -f b99test.mak rebuild
	@$(MAKE) --no-print-directory -f srbios.mak rebuild
	@$(MAKE) --no-print-directory -f srtest.mak rebuild
	@$(MAKE) --no-print-directory -f carnbios.mak rebuild
	@$(MAKE) --no-print-directory -f carntest.mak rebuild
	@$(MAKE) --no-print-directory -f vegabios.mak rebuild
	@$(MAKE) --no-print-directory -f vegatest.mak rebuild

clobber:
	@$(MAKE) --no-print-directory -f nbabios.mak clobber
	@$(MAKE) --no-print-directory -f nbatest.mak clobber
	@$(MAKE) --no-print-directory -f nflbios.mak clobber
	@$(MAKE) --no-print-directory -f nfltest.mak clobber
	@$(MAKE) --no-print-directory -f b99bios.mak clobber
	@$(MAKE) --no-print-directory -f b99ltest.mak clobber
	@$(MAKE) --no-print-directory -f srbios.mak clobber
	@$(MAKE) --no-print-directory -f srtest.mak clobber
	@$(MAKE) --no-print-directory -f carnbios.mak clobber
	@$(MAKE) --no-print-directory -f carntest.mak clobber
	@$(MAKE) --no-print-directory -f vegabios.mak clobber
	@$(MAKE) --no-print-directory -f vegatest.mak clobber

clean:
	@$(MAKE) --no-print-directory -f nbabios.mak clean
	@$(MAKE) --no-print-directory -f nbatest.mak clean
	@$(MAKE) --no-print-directory -f nflbios.mak clean
	@$(MAKE) --no-print-directory -f nfltest.mak clean
	@$(MAKE) --no-print-directory -f b99bios.mak clean
	@$(MAKE) --no-print-directory -f b99ltest.mak clean
	@$(MAKE) --no-print-directory -f srbios.mak clean
	@$(MAKE) --no-print-directory -f srtest.mak clean
	@$(MAKE) --no-print-directory -f carnbios.mak clean
	@$(MAKE) --no-print-directory -f carntest.mak clean
	@$(MAKE) --no-print-directory -f vegabios.mak clean
	@$(MAKE) --no-print-directory -f vegatest.mak clean

rebuild:
	@$(MAKE) --no-print-directory -f nbabios.mak rebuild
	@$(MAKE) --no-print-directory -f nbatest.mak rebuild
	@$(MAKE) --no-print-directory -f nflbios.mak rebuild
	@$(MAKE) --no-print-directory -f nfltest.mak rebuild
	@$(MAKE) --no-print-directory -f b99bios.mak rebuild
	@$(MAKE) --no-print-directory -f b99test.mak rebuild
	@$(MAKE) --no-print-directory -f srbios.mak rebuild
	@$(MAKE) --no-print-directory -f srtest.mak rebuild
	@$(MAKE) --no-print-directory -f carnbios.mak rebuild
	@$(MAKE) --no-print-directory -f carntest.mak rebuild
	@$(MAKE) --no-print-directory -f vegabios.mak rebuild
	@$(MAKE) --no-print-directory -f vegatest.mak rebuild
