#line 2 "sdl2seq.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 19
#define YY_END_OF_BUFFER 20
static yyconst short int yy_accept[229] =
    {   0,
        0,    0,    0,    0,   20,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   17,   17,   17,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    8,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    6,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    4,    0,    0,    2,    0,    0,    5,    0,
        0,    3,    0,    0,    0,    0,    1,    4,    2,    5,

        3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    4,    0,    2,    0,    5,    0,    3,    0,    0,
        0,   16,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   16,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   16,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    7,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    9,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   10,    0,   11,    0,   12,    0,    0,    0,
        0,    0,    0,    0,   13,   14,   15,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    1,    7,
        8,    1,    9,   10,   11,   12,    1,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    1,   14,    1,
       15,    1,    1,    1,   16,   16,   17,   18,   19,   20,
       21,   22,   23,   16,   16,   24,   25,   26,   27,   28,
       16,   29,   30,   31,   16,   16,   16,   32,   33,   34,
        1,    1,    1,    1,   35,    1,   36,   16,   37,   38,

       39,   16,   40,   41,   42,   16,   16,   43,   44,   45,
       46,   47,   16,   48,   49,   50,   51,   52,   16,   53,
       54,   16,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    2,    1,    2,    1,    3,    1,    1,    1,    1,
        1,    3,    3,    1,    1,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4
    } ;

static yyconst short int yy_base[239] =
    {   0,
        0,   34,    0,    1,  316,  317,  274,  278,  259,  285,
      287,  287,  282,  266,  261,  317,  292,  266,  268,  255,
      255,  276,  277,  278,  280,  257,  258,  317,  247,  249,
      257,  253,  263,  262,  267,  269,  246,  247,  235,  239,
      239,  278,  252,  317,  276,  275,  274,  273,  237,  236,
      235,  268,  253,  238,  237,  215,  214,  214,  223,  215,
      246,  233,  247,  246,  245,  244,  251,  253,  217,  219,
      224,    0,    3,    6,    9,    0,  248,  204,  211,  247,
       11,  236,   13,   15,  235,   17,   19,  234,   21,   23,
      233,   26,   53,    8,  210,  240,  317,   30,   48,   49,

       57,   32,  230,   70,  238,  237,  236,  202,  212,   80,
       81,   86,   89,   99,  103,   17,   75,   79,  186,  190,
      222,  221,  220,  219,  218,  217,  216,  215,  108,   46,
      214,   65,  180,  177,  178,  175,  176,  173,  172,  181,
      205,  118,  110,  167,  180,  165,  178,  163,  176,  159,
      171,  121,  173,  163,  171,  161,  169,  159,  164,  197,
      188,  187,  149,  149,  147,  147,  145,  145,    1,  189,
      153,  148,  151,  146,  149,  144,  122,  179,  180,  148,
      178,  146,  176,  144,  123,  175,  174,  127,  172,  125,
      170,  123,    0,  141,  108,  139,  106,  137,  104,    0,

      138,  136,  136,  134,  133,  131,    0,  131,    0,  129,
        0,  107,    0,   79,    0,   78,    0,   66,   59,    6,
        3,    0,    0,    0,    0,    0,    0,  317,  149,  153,
      156,    2,  158,  160,  162,  164,  166,  168
    } ;

static yyconst short int yy_def[239] =
    {   0,
      229,  229,  230,  230,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,

      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  231,  228,  228,  228,
      228,  228,  228,  228,  231,  228,  228,  228,  228,  228,
      228,  228,  232,  228,  228,  228,  228,  228,  228,  232,

      228,  228,  228,  228,  228,  228,  233,  228,  234,  228,
      235,  228,  233,  228,  234,  228,  235,  228,  228,  228,
      228,  236,  237,  238,  236,  237,  238,    0,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228
    } ;

static yyconst short int yy_nxt[372] =
    {   0,
      228,   93,  177,   93,  177,  200,  224,   17,   17,  223,
       81,   82,   83,   84,   85,   86,   87,   88,   89,   90,
       91,   92,   82,   83,   82,   83,   85,   86,   85,   86,
       88,   89,   88,   89,   91,   92,    7,   91,   92,  105,
      106,  107,   98,  103,  104,  133,    8,  134,  110,    9,
       10,   18,   18,   11,   93,   12,   93,  131,  132,   13,
       99,  100,  222,  102,  103,  104,  111,  112,  110,  101,
        7,  115,  221,  115,   14,  113,  131,  132,   15,  115,
        8,  103,  104,    9,  220,  219,  111,  112,  121,  123,
      121,  123,  122,  124,  125,  113,  125,  127,  126,  127,

      115,  128,  115,  135,  115,  136,  115,  137,  115,  138,
      218,  114,  115,  130,  131,  132,  141,  129,  141,  115,
      142,  115,  143,  177,  228,  177,  228,  115,  152,  161,
      142,  161,  216,  162,  214,  212,  211,  129,  210,  209,
      208,  207,  206,  205,  204,  203,  202,  201,  152,    6,
        6,    6,    6,   16,   16,   16,   16,  185,  185,  185,
      213,  213,  215,  215,  217,  217,  225,  225,  226,  226,
      227,  227,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  187,  186,  184,  183,  182,  181,
      180,  179,  178,  176,  175,  174,  173,  172,  171,  162,

      162,  170,  169,  168,  167,  166,  165,  164,  163,  160,
      159,  158,  157,  156,  155,  154,  153,  142,  151,  150,
      149,  148,  147,  146,  145,  144,  143,  128,  128,  126,
      126,  124,  124,  122,  122,  140,  139,  120,  119,  118,
      117,  116,  114,  109,  108,  101,  100,   99,   98,   97,
       96,   95,   94,   80,   79,   78,   77,   76,   75,   74,
       73,   72,   71,   70,   69,   68,   67,   66,   65,   64,
       63,   62,   61,   60,   59,   58,   57,   56,   55,   54,
       53,   52,   51,   50,   49,   48,   47,   46,   45,   44,
       43,   42,   41,   40,   39,   38,   37,   36,   35,   34,

       33,   32,   31,   30,   29,   28,   27,   26,   25,   24,
       23,   22,   21,   20,   19,  228,    5,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228
    } ;

static yyconst short int yy_chk[372] =
    {   0,
        0,   76,  169,   76,  169,  232,  221,    3,    4,  220,
       72,   72,   72,   73,   73,   73,   74,   74,   74,   75,
       75,   75,   81,   81,   83,   83,   84,   84,   86,   86,
       87,   87,   89,   89,   90,   90,    1,   92,   92,   94,
       94,   94,   98,  102,  102,  116,    1,  116,   98,    1,
        2,    3,    4,    2,   93,    2,   93,  130,  130,    2,
       99,  100,  219,   93,   93,   93,   99,  100,   98,  101,
        2,  104,  218,  104,    2,  101,  132,  132,    2,  104,
        2,  104,  104,    2,  216,  214,   99,  100,  110,  111,
      110,  111,  110,  111,  112,  101,  112,  113,  112,  113,

      114,  113,  114,  117,  115,  117,  115,  118,  114,  118,
      212,  114,  115,  115,  115,  115,  129,  114,  129,  142,
      129,  142,  143,  177,  185,  177,  185,  142,  143,  152,
      142,  152,  210,  152,  208,  206,  205,  114,  204,  203,
      202,  201,  199,  198,  197,  196,  195,  194,  143,  229,
      229,  229,  229,  230,  230,  230,  230,  231,  231,  231,
      233,  233,  234,  234,  235,  235,  236,  236,  237,  237,
      238,  238,  192,  191,  190,  189,  188,  187,  186,  184,
      183,  182,  181,  180,  179,  178,  176,  175,  174,  173,
      172,  171,  170,  168,  167,  166,  165,  164,  163,  162,

      161,  160,  159,  158,  157,  156,  155,  154,  153,  151,
      150,  149,  148,  147,  146,  145,  144,  141,  140,  139,
      138,  137,  136,  135,  134,  133,  131,  128,  127,  126,
      125,  124,  123,  122,  121,  120,  119,  109,  108,  107,
      106,  105,  103,   96,   95,   91,   88,   85,   82,   80,
       79,   78,   77,   71,   70,   69,   68,   67,   66,   65,
       64,   63,   62,   61,   60,   59,   58,   57,   56,   55,
       54,   53,   52,   51,   50,   49,   48,   47,   46,   45,
       43,   42,   41,   40,   39,   38,   37,   36,   35,   34,
       33,   32,   31,   30,   29,   27,   26,   25,   24,   23,

       22,   21,   20,   19,   18,   17,   15,   14,   13,   12,
       11,   10,    9,    8,    7,    5,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  228,  228,  228,  228,  228,  228,
      228
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sdl2seq.l"
#define INITIAL 0
#line 2 "sdl2seq.l"
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <ctype.h>
#include <string.h>

#include "lookup.h"

#define FALSE	0
#define TRUE	!FALSE


typedef int boolean;
typedef float matrix[3][3];
typedef float quat[4];

void init_curve( char * );
void end_curve( void );
void add_point( char * );

void adjust_quat( quat, quat );
void mxm( matrix, matrix, matrix );
void rotx( float, matrix );
void roty( float, matrix );
void rotz( float, matrix );
int best_lookup( float );
int new_node( char * );
void assign_channel( int, char * );
void mat2quat( matrix, quat );
void quat2mat( quat, matrix );
void print_help( void );
unsigned long crc(unsigned char *data, int len);
void print_mat( matrix );
void print_quat( quat );

int cur_node;
boolean flip = FALSE;
boolean	compress = FALSE;
float	yrot = 0.0f;
float	highy = 0.0f;

#define CV 1

#line 567 "sdl2seq.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 51 "sdl2seq.l"


#line 724 "sdl2seq.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 229 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 317 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 53 "sdl2seq.l"
compress = TRUE;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 54 "sdl2seq.l"
yrot = atof( yytext + 7 );
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 55 "sdl2seq.l"
yrot = atof( yytext + 7 );
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 56 "sdl2seq.l"
highy = atof( yytext + 7 );
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 57 "sdl2seq.l"
highy = atof( yytext + 7 );
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 58 "sdl2seq.l"
flip = TRUE;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 59 "sdl2seq.l"
{ BEGIN CV; init_curve( yytext ); };
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "sdl2seq.l"
{ BEGIN 0; end_curve(); };
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "sdl2seq.l"
cur_node = new_node( yytext+18 );
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 62 "sdl2seq.l"
assign_channel( 0, yytext+21 );
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 63 "sdl2seq.l"
assign_channel( 1, yytext+21 );
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 64 "sdl2seq.l"
assign_channel( 2, yytext+21 );
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "sdl2seq.l"
assign_channel( -3, yytext+24 );
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 66 "sdl2seq.l"
assign_channel( -2, yytext+24 );
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 67 "sdl2seq.l"
assign_channel( -1, yytext+24 );
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 68 "sdl2seq.l"
add_point( yytext );
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 69 "sdl2seq.l"
;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 70 "sdl2seq.l"
;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 72 "sdl2seq.l"
ECHO;
	YY_BREAK
#line 903 "sdl2seq.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CV):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 229 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 229 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 228);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 72 "sdl2seq.l"

typedef struct _VECTOR
{
	float	x,y,z;
} VECTOR;

typedef struct _CURVE
{
	char	name[32];
	int		count;
	float	*pdata;
} CURVE;

struct seq_header
{
	char	name[16];
	int		nframes;
	int		nlimbs;
	int		flags;
};

#define A_COMPRESSED	0x1


#define X	0
#define Y	1
#define Z	2
#define W	3

#define LIMB_COUNT	15
#define MAX_FRAMES	512
#define MAX_CURVES  128

int flip_limbs[LIMB_COUNT] = { 0,0,1,1,1,1,1,1,0,1,1,1,1,1,1 };

char *limb_names[LIMB_COUNT] =
{
	"BIPED", "BACK", "RT_SHOULDER", "RT_ELBOW", "RT_WRIST",
	"LF_SHOULDER", "LF_ELBOW", "LF_WRIST", "NECK",
	"RT_HIP", "RT_KNEE", "RT_ANKLE", "LF_HIP", "LF_KNEE", "LF_ANKLE",
};

char *limb_names_flip[LIMB_COUNT] =
{
	"BIPED", "BACK", "LF_SHOULDER", "LF_ELBOW", "LF_WRIST",
	"RT_SHOULDER", "RT_ELBOW", "RT_WRIST", "NECK",
	"LF_HIP", "LF_KNEE", "LF_ANKLE", "RT_HIP", "RT_KNEE", "RT_ANKLE",
};

int limb_map[LIMB_COUNT][3];
int	translate[6];
CURVE curves[MAX_CURVES];
float points[1024];
int npoints, ncurves = 0;
int hits[256];

float xlate[MAX_FRAMES][3];
float frame0[LIMB_COUNT][4];
char frames[MAX_FRAMES*LIMB_COUNT][4];			/* compressed quats */
float uframes[MAX_FRAMES*LIMB_COUNT][4];		/* raw (precompressed) quats */
float ucframes[MAX_FRAMES*LIMB_COUNT][4];		/* reconstituted quats */
int frame_count;
boolean	write_crcs = FALSE;
unsigned long crcs[MAX_FRAMES];

typedef enum { PS_NONE, PS_OUTFILE, PS_NAME, PS_SCALE, PS_CRC,
				PS_YROT } pstate;
typedef enum { OM_TEXT, OM_BINARY } outmode;


/**********************************************************************/
int main( int argc, char *args[] )
{
	int		i, j;
	matrix	m1,m2,m3,m4,m5,m6,m7;
	quat	q1;
	FILE	*outfile, *infile, *crcfile;
	struct seq_header header;
	char	*outfspec = NULL, *seqname = NULL, *infspec = NULL;
	char	*crcfspec = NULL;
	char	root[16], *cp;
	char	tbuf[128];
	pstate	pmode = PS_NONE;
	outmode	output_mode = OM_BINARY;
	float	xlate_sf = 1.0f;

	float	prev[15][4];

	/* parse command flags */
	for( i = 1; i < argc; i++ )
	{
		switch( args[i][0] )
		{
			case '-':
				switch( args[i][1] )
				{
					case 'o':	/* output filename */
						if( args[i][2] )
							outfspec = &args[i][2];
						else
							pmode = PS_OUTFILE;
						break;
					case 'n':	/* sequence name */
						if( args[i][2] )
							seqname = &args[i][2];
						else
							pmode = PS_NAME;
						break;
					case 's':	/* set translation scale factor */
						if( args[i][2] )
							xlate_sf = atof( &args[i][2] );
						else
							pmode = PS_SCALE;
						break;
					case 't':
						output_mode = OM_TEXT;
						break;
					case 'c':
						write_crcs = TRUE;
						if( args[i][2] )
							crcfspec = &args[i][2];
						else
							pmode = PS_CRC;
						break;
					case 'k':	/* kompress */
						compress = TRUE;
						break;
					case 'f':	/* flip (in x) */
						flip = TRUE;
						break;
					case 'h':	/* help */
						print_help();
						exit( 1 );
						break;
					case 'y':	/* top-level y rotate */
						if( args[i][2] )
							yrot = atof( &args[i][2] );
						else
							pmode = PS_YROT;
						break;
					default:
						fprintf(stderr,"WARNING: Unrecognized command li"
								"ne option: %s\n", args[i] );
						break;
				}
				break;
			default:
				switch( pmode )
				{
					case PS_OUTFILE:
						outfspec = args[i];
						pmode = PS_NONE;
						break;
					case PS_NAME:
						seqname = args[i];
						pmode = PS_NONE;
						break;
					case PS_SCALE:
						xlate_sf = atof( args[i] );
						pmode = PS_NONE;
						break;
					case PS_CRC:
						crcfspec = args[i];
						pmode = PS_NONE;
						break;
					case PS_YROT:
						yrot = atof( args[i] );
						pmode = PS_NONE;
						break;
					default:
						if( infspec )
						{
							fprintf(stderr,"ERROR: Too many input files speci"
									"fied.\n" );
							exit( 1 );
						}
						else
							infspec = args[i];
						break;
				}
				break;
		}
	}

	if( !infspec )
	{
		fprintf( stderr, "ERROR: Must specify one input file.\n" );
		exit( 1 );
	}

	strncpy( root, infspec, 16 );
	root[15] = '\0';
	if(( cp = strchr( root, '.' )))
		*cp = '\0';

	if( !seqname )
		seqname = root;

	if( !outfspec )
	{
		sprintf( tbuf, "%s.seq", root );
		outfspec = tbuf;
	}

	infile = fopen( infspec, "rt" );
	if( infile == NULL )
	{
		fprintf( stderr, "Error opening file %s for reading.\n", infspec );
		exit( 1 );
	}

	outfile = fopen( outfspec, ( output_mode == OM_BINARY) ? "wb" : "wt" );
	if( outfile == NULL )
	{
		fprintf( stderr, "Error opening file %s for writing.\n", outfspec );
		exit( 1 );
	}

	if( write_crcs )
	{
		crcfile = fopen( crcfspec, "wt" );
		if( crcfile == NULL )
		{
			fprintf( stderr, "Error opening file %s for writing.\n", crcfspec );
			exit( 1 );
		}
	}

	/* initialize limb_map */
	for( i = 0; i < LIMB_COUNT; i++ )
	{
		limb_map[i][0] = -1;
		limb_map[i][1] = -1;
		limb_map[i][2] = -1;
	}

	translate[0] = -1;
	translate[1] = -1;
	translate[2] = -1;
	translate[3] = -1;
	translate[4] = -1;
	translate[5] = -1;

	/* read curves from stdin */
	yyin = infile;
	yylex();

	/* holler if any channels are missing */
	for( i = 0; i < LIMB_COUNT; i++ )
	{
		char xyz[] = { 'X', 'Y', 'Z' };

		for( j = 0; j < 3; j++ )
		{
			if( limb_map[i][j] == -1 )
			{
				fprintf( stderr, "Warning! Channel %s has no %c rotate cha"
						"nnel.\n", limb_names[i], xyz[j] );
				limb_map[i][j] = ncurves;
			}
		}
	}

	/* make sure all cuves have the same count */
	for( i = 1; i < ncurves; i++ )
	{
		if( curves[i].count != curves[i-1].count )
		{
			fprintf( stderr, "Error!  Curves %s and %s don't have the same "
					"number of data points. (%d and %d)\n", curves[i-1].name,
					curves[i].name, curves[i-1].count, curves[i].count );
			exit( 1 );
		}
	}

	frame_count = curves[0].count;

	/* put a zero curve at the end of the list */
	curves[ncurves].pdata = (float *)malloc( curves[0].count * sizeof( float ));
	for( i = 0; i < curves[0].count; i++ )
		curves[ncurves].pdata[i] = 0.0f;
	sprintf( curves[ncurves].name, "zero" );
	curves[ncurves].count = curves[0].count;

	/* initialize prev */
	for( i = 0; i < 15; i++ )
	{
		prev[i][0] = 0.0f;
		prev[i][1] = 0.0f;
		prev[i][2] = 0.0f;
		prev[i][3] = 0.0f;
	}

	for( i = 0; i < frame_count; i++ )
	{
		float x,y,z;
		float theta = yrot /360.0f * 2.0f * 3.14159f;

		x = curves[translate[0]].pdata[i] * xlate_sf;
		y = curves[translate[1]].pdata[i] * xlate_sf;
		z = curves[translate[2]].pdata[i] * xlate_sf;

		xlate[i][0] = (z*sin(theta) + x*cos(theta));
		xlate[i][1] = y;
		xlate[i][2] = z*cos(theta) - x*sin(theta);

		x = 0.0f;
		y = 0.0f;
		z = 0.0f;

		theta = highy /360.0f * 2.0f * 3.14159f;

		if( translate[3] != -1 )
			x = curves[translate[3]].pdata[i] * xlate_sf;

		if( translate[4] != -1 )
			y = curves[translate[4]].pdata[i] * xlate_sf;

		if( translate[5] != -1 )
			z = curves[translate[5]].pdata[i] * xlate_sf;

		xlate[i][0] += (z*sin(theta) + x*cos(theta));
		xlate[i][1] += y;
		xlate[i][2] += z*cos(theta) - x*sin(theta);

		xlate[i][0] *= (flip ? -1.0f : 1.0f);
	}

	for( i = 0; i < frame_count; i++ )	/* frame loop */
	{
		for( j = 0; j < LIMB_COUNT; j++ )			/* limb loop */
		{
			quat	fq;
			float	matches[4];
			int		fits[4];
			float	r3,r4,r5,r6;

			/* build a composite matrix for this rotation */
			rotx( r3 = curves[limb_map[j][0]].pdata[i], m3 );
			roty( r4 = curves[limb_map[j][1]].pdata[i] * (flip ? -1.0f : 1.0f), m4 );
			rotz( r5 = curves[limb_map[j][2]].pdata[i] * (flip ? -1.0f : 1.0f), m5 );
			if( j )
				roty( r6 = 0.0f, m6 );
			else
				roty( r6 = (yrot * (flip ? -1.0f : 1.0f)), m6 );

			roty( 0.0f, m2 );

			mxm( m6, m5, m7 );
			mxm( m7, m4, m1 );
			mxm( m1, m3, m7 );
			mxm( m7, m2, m1 );

			mat2quat( m1, fq );

			if( i == 0 )
			{
				prev[j][0] = fq[0];
				prev[j][1] = fq[1];
				prev[j][2] = fq[2];
				prev[j][3] = fq[3];

				frame0[j][0] = fq[0];
				frame0[j][1] = fq[1];
				frame0[j][2] = fq[2];
				frame0[j][3] = fq[3];

				uframes[j][0] = fq[0];
				uframes[j][1] = fq[1];
				uframes[j][2] = fq[2];
				uframes[j][3] = fq[3];

				ucframes[j][0] = fq[0];
				ucframes[j][1] = fq[1];
				ucframes[j][2] = fq[2];
				ucframes[j][3] = fq[3];
			}
			else
			{

				// if -fq[i] is a better match to fq[i-1] than fq[i], use it
				adjust_quat( fq, prev[j] );

				uframes[(i*15)+j][0] = fq[0];
				uframes[(i*15)+j][1] = fq[1];
				uframes[(i*15)+j][2] = fq[2];
				uframes[(i*15)+j][3] = fq[3];

				fits[0] = best_lookup( fq[0] - prev[j][0] );
				fits[1] = best_lookup( fq[1] - prev[j][1] );
				fits[2] = best_lookup( fq[2] - prev[j][2] );
				fits[3] = best_lookup( fq[3] - prev[j][3] );

				matches[0] = lookup[fits[0]];
				matches[1] = lookup[fits[1]];
				matches[2] = lookup[fits[2]];
				matches[3] = lookup[fits[3]];

				prev[j][0] += matches[0];
				prev[j][1] += matches[1];
				prev[j][2] += matches[2];
				prev[j][3] += matches[3];

				ucframes[(i*15)+j][0] = prev[j][0];
				ucframes[(i*15)+j][1] = prev[j][1];
				ucframes[(i*15)+j][2] = prev[j][2];
				ucframes[(i*15)+j][3] = prev[j][3];

				frames[((i-1)*15)+j][0] = fits[0];
				frames[((i-1)*15)+j][1] = fits[1];
				frames[((i-1)*15)+j][2] = fits[2];
				frames[((i-1)*15)+j][3] = fits[3];

#if 0
				/* coverage check */
				hits[fits[0]] ++;
				hits[fits[1]] ++;
				hits[fits[2]] ++;
				hits[fits[3]] ++;
#endif
				q1[0] = ucframes[(i*15)+j][0];
				q1[1] = ucframes[(i*15)+j][1];
				q1[2] = ucframes[(i*15)+j][2];
				q1[3] = ucframes[(i*15)+j][3];
				quat2mat( q1, m2 );

#if 0
				if((j==3) && (i<=25) && (i>=16))
				{
					printf( "f%d  l%d:  rotx(%f) roty(%f) rotz(%f) roty(%f)\n", i, j, r3, r4, r5, r6 );

					printf( "resulting matrix:  %9f %9f %9f  %9f %9f %9f   %9f %9f %9f - %9f\n",
						m1[0][0], m1[0][1], m1[0][2],
						m1[1][0], m1[1][1], m1[1][2],
						m1[2][0], m1[2][1], m1[2][2],
						m1[0][0] + m1[1][1] + m1[2][2] );
					printf( "quaternion:        %9f %9f %9f %9f\n", fq[0], fq[1], fq[2], fq[3] );
					printf( "decompressed quat: %9f %9f %9f %9f\n", q1[0], q1[1], q1[2], q1[3] );
					printf( "decompressed mat:  %9f %9f %9f  %9f %9f %9f   %9f %9f %9f\n",
						m2[0][0], m2[0][1], m2[0][2],
						m2[1][0], m2[1][1], m2[1][2],
						m2[2][0], m2[2][1], m2[2][2] );
				}
#endif
			}
		}

		/* compute crc */
		crcs[i] = crc( (char *)(uframes[15*i]), 240 );
	}

	/* output */
	strcpy( header.name, seqname );

	for( i = 0; i < strlen( header.name ); i++ )
		header.name[i] = toupper( header.name[i] );
	while( i < 16 )
		header.name[i++] = '\0';

	header.nframes = frame_count;
	header.nlimbs = 15;
	header.flags = 0;
	if( compress )
		header.flags |= A_COMPRESSED;

	if( output_mode == OM_BINARY )
	{
		/* header */
		fwrite( &header, sizeof( struct seq_header ), 1, outfile );

		/* translation */
		fwrite( xlate, sizeof( float ), header.nframes * 3, outfile );

		/* frame 0 */
		fwrite( frame0, sizeof( float ), header.nlimbs * 4, outfile );

		/* other frames */
		if( compress )
		{
			fwrite( frames, sizeof( char ), header.nlimbs * (header.nframes-1) * 4,
					outfile );
		}
		else
		{
			fwrite( uframes + header.nlimbs, sizeof( float ), header.nlimbs * (header.nframes-1) * 4,
					outfile );
		}
	}
	else
	{
		/* header */
		fprintf( outfile, "name: %s  frames: %d  limbs: %d\n", header.name,
				header.nframes, header.nlimbs );

		/* translation */

		/* frame 0 */
		fprintf( outfile, "\nframe 0: crc: 0x%lX\t\txlate: %9f %9f %9f\n", crcs[0],
				xlate[0][0], xlate[0][1], xlate[0][2] );
		for( i = 0; i < header.nlimbs; i++ )
			fprintf( outfile, " n/a  n/a  n/a  n/a | %9f %9f %9f %9f\n",
					frame0[i][0], frame0[i][1], frame0[i][2], frame0[i][3] );

		/* other frames */
		for( i = 0; i < header.nframes-1; i++ )
		{
			fprintf( outfile, "\nframe %d: crc: 0x%lX\t\t xlate: %9f %9f %9f\n", i+1, crcs[i+1],
					xlate[i+1][0], xlate[i+1][1], xlate[i+1][2] );
			if( compress )
			{
				for( j = 0; j < header.nlimbs; j++ )
				{
					unsigned char n0,n1,n2,n3;	/* compress qt indices */
					float	v0,v1,v2,v3;	/* pre-compressed result */
					float	t0,t1,t2,t3;	/* compressed + uncompressed result */
					float	d0,d1,d2,d3;	/* difference between tX and vX (loss ) */
					float	n;

					n0 = frames[i * header.nlimbs + j][0];
					n1 = frames[i * header.nlimbs + j][1];
					n2 = frames[i * header.nlimbs + j][2];
					n3 = frames[i * header.nlimbs + j][3];

	 				v0 = uframes[(i+1) * header.nlimbs + j][0];
	 				v1 = uframes[(i+1) * header.nlimbs + j][1];
	 				v2 = uframes[(i+1) * header.nlimbs + j][2];
	 				v3 = uframes[(i+1) * header.nlimbs + j][3];

	 				t0 = ucframes[(i+1) * header.nlimbs + j][0];
	 				t1 = ucframes[(i+1) * header.nlimbs + j][1];
	 				t2 = ucframes[(i+1) * header.nlimbs + j][2];
	 				t3 = ucframes[(i+1) * header.nlimbs + j][3];

					d0 = t0 - v0;
					d1 = t1 - v1;
					d2 = t2 - v2;
					d3 = t3 - v3;

					n = sqrt( t0 * t0 + t1 * t1 + t2 * t2 + t3 * t3 );

					fprintf( outfile, "%4u %4u %4u %4u | %9f %9f %9f %9f | %9f %9f %9f %9f | %9f %9f %9f %9f | %9f%s",
						0xff & n0, 0xff & n1, 0xff & n2, 0xff & n3,
						v0, v1, v2, v3,
						t0, t1, t2, t3,
						d0, d1, d2, d3,
						n,
						((( n >= 1.01 ) || ( n <= 0.99 )) ? " BAD\n" : "\n" )
						);
				}
			}
			else
			{
				for( j = 0; j < header.nlimbs; j++ )
				{
					float	v0,v1,v2,v3;	/* pre-compressed result */

	 				v0 = uframes[(i+1) * header.nlimbs + j][0];
	 				v1 = uframes[(i+1) * header.nlimbs + j][1];
	 				v2 = uframes[(i+1) * header.nlimbs + j][2];
	 				v3 = uframes[(i+1) * header.nlimbs + j][3];

					fprintf( outfile, "%4s %4s %4s %4s | %9f %9f %9f %9f | %9f %9f %9f %9f | %9f %9f %9f %9f | %9f\n",
						"n/a", "n/a", "n/a", "n/a",
						v0, v1, v2, v3,
						v0, v1, v2, v3,
						0.0f, 0.0f, 0.0f, 0.0f,
						sqrt( v0 * v0 + v1 * v1 + v2 * v2 + v3 * v3 )
						);
				}
			}
		}
	}

	fclose( outfile );

	/* write the crc file */
	if( write_crcs )
	{
		/* header */
		fprintf( crcfile, "name: %s  frames: %d  limbs: %d\n\n", header.name,
				header.nframes, header.nlimbs );

		/* frames */
		for( i = 0; i < frame_count; i++ )
			fprintf( crcfile ,"%3d %9f\t%9f\t%9f\t0x%0lX\n", i, xlate[i][0],
				xlate[i][1], xlate[i][2], crcs[i] );

		fclose( crcfile );
	}

	return 0;
}

/****************************************************************************/

void init_curve( char *text )
{
	sscanf( text, "parameter_curve %s (", curves[ncurves].name );
	npoints = 0;
}

/****************************************************************************/

void end_curve( void )
{
	int		i;
	float	*pd;

	/* allocate space for curve data */
	pd = (float *)malloc( sizeof( float ) * npoints );

	for( i = 0; i < npoints; i++ )
	{
		pd[i] = points[i];
	}

	curves[ncurves].pdata = pd;
	curves[ncurves].count = npoints;

	ncurves++;
}

/****************************************************************************/

void add_point( char *text )
{
	char *p;

	/* find start of second number in string */
	p = text;
	while( !isdigit( *p ))
		p++;

	while( *p != ' ' && *p != '\t' )
		p++;

	while( !isdigit( *p ) && *p != '-' )
		p++;

	points[npoints] = atof( p );
	npoints++;
}

/****************************************************************************/

int new_node( char *text )
{
	int i;

	/* figure out which node this is */
	for( i = 0; i < LIMB_COUNT; i++ )
	{
		if( !strcmp( (flip ? limb_names_flip[i] : limb_names[i]), text ))
			return i;
	}

	return -1;
}

/****************************************************************************/

void assign_channel( int channel, char *skey )
{
	int i;

	for( i = 0; (i < ncurves) && (strcmp( skey, curves[i].name)); i++ );

	if( channel >= 0 )
		limb_map[cur_node][channel] = i;
	else
	{
		switch( cur_node )
		{
			case 0:
				translate[channel+3] = i;
				break;
			case -1:
				translate[channel+6] = i;
				break;
			default:
				printf( "Warning: curve %s is translation data for non-root "
						"node.\n", skey );
				break;
		}
	}
}

/****************************************************************************/

void mxm( matrix m1, matrix m2, matrix d )
{
	int i, j;

	for( i = 0; i < 3; i++ )
	{
		for( j = 0; j < 3; j++ )
		{
			d[i][j] = m1[i][0] * m2[0][j] +
					  m1[i][1] * m2[1][j] +
					  m1[i][2] * m2[2][j];
		}
	}
}

/****************************************************************************/

void rotx( float deg, matrix m )
{
	float rad;

	rad = deg * 2.0f * 3.14159f / 360.0f;

	m[0][0] = 1.0f;
	m[0][1] = 0.0f;
	m[0][2] = 0.0f;

	m[1][0] = 0.0f;
	m[1][1] = cos( rad );
	m[1][2] = -1.0f * sin( rad );

	m[2][0] = 0.0f;
	m[2][1] = sin( rad );
	m[2][2] = cos( rad );
}

/****************************************************************************/

void roty( float deg, matrix m )
{
	float rad;

	rad = deg * 2.0f * 3.14159f / 360.0f;

	m[0][0] = cos( rad );
	m[0][1] = 0.0f;
	m[0][2] = sin( rad );

	m[1][0] = 0.0f;
	m[1][1] = 1.0f;
	m[1][2] = 0.0f;

	m[2][0] = -1.0f * sin( rad );
	m[2][1] = 0.0f;
	m[2][2] = cos( rad );
}

/****************************************************************************/

void rotz( float deg, matrix m )
{
	float rad;

	rad = deg * 2.0f * 3.14159f / 360.0f;

	m[0][0] = cos( rad );
	m[0][1] = -1.0f * sin( rad );
	m[0][2] = 0.0f;

	m[1][0] = sin( rad );
	m[1][1] = cos( rad );
	m[1][2] = 0.0f;

	m[2][0] = 0.0f;
	m[2][1] = 0.0f;
	m[2][2] = 1.0f;
}

/****************************************************************************/

int yywrap( void )
{
	return 1;
}

/****************************************************************************/
void mat2quat( matrix mat, quat q )
{
	float	tr,s;
	int		i,j,k;
	int		nxt[3] = {Y,Z,X};
	float	mag;

	tr = mat[0][0] + mat[1][1] + mat[2][2];
	if( tr > 0.0f )
	{
		s = sqrt( tr + 1.0f );
		q[W] = s * 0.5f;
		s = 0.5f / s;
		q[X] = -(mat[1][2] - mat[2][1]) * s;
		q[Y] = -(mat[2][0] - mat[0][2]) * s;
		q[Z] = -(mat[0][1] - mat[1][0]) * s;
	}
	else
	{
		i = X;
		if( mat[Y][Y] > mat[X][X] )
			i = Y;
		if( mat[Z][Z] > mat[i][i] )
			i = Z;

		j = nxt[i];
		k = nxt[j];

		s = sqrt((mat[i][i] - (mat[j][j]+mat[k][k])) + 1.0f);
		q[i] = s*0.5f;
		s = 0.5f / s;
		q[W] =-(mat[j][k] - mat[k][j]) * s;
		q[j] =(mat[i][j] + mat[j][i]) * s;
		q[k] =(mat[i][k] + mat[k][i]) * s;
	}

	// normalize
	mag = sqrt( q[X]*q[X] + q[Y]*q[Y] + q[Z]*q[Z] + q[W]*q[W] );

	q[X] /= mag;
	q[Y] /= mag;
	q[Z] /= mag;
	q[W] /= mag;
}

/****************************************************************************/
void quat2mat( quat q, matrix m )
{
	float	s,xs,ys,zs,wx,wy,wz,xx,xy,xz,yy,yz,zz;

	s = 2.0f;

	xs = q[X]*s;	ys = q[Y]*s;	zs = q[Z]*s;
	wx = q[W]*xs;	wy = q[W]*ys;	wz = q[W]*zs;
	xx = q[X]*xs;	xy = q[X]*ys;	xz = q[X]*zs;
	yy = q[Y]*ys;	yz = q[Y]*zs;	zz = q[Z]*zs;

	m[0][0] = 1.0f-(yy+zz);	m[0][1] = xy-wz;		m[0][2] = xz+wy;
	m[1][0] = xy+wz;		m[1][1] = 1.0f-(xx+zz);	m[1][2] = yz-wx;
	m[2][0] = xz-wy;		m[2][1] = yz+wx;		m[2][2] = 1.0f-(xx+yy);
}

/****************************************************************************/
int best_lookup( float val )
{
	int		i;

	/* take the highest value that doesn't exceed the target */

	for( i = 1; i < 256; i++ )
	{
		if( lookup[i]  > val )
			return i-1;
	}

	return 255;
}

/****************************************************************************/
void print_help( void )
{
	printf( "sdl2seq [options] infile\n" );
	printf( " -o <file>     write output to <file>\n" );
	printf( " -n <name>     sequence name\n" );
	printf( " -s <factor>   scale translation data\n" );
	printf( " -t            text output (debug only - not C source\n" );
	printf( " -c <file>     write frame crc's to <file>\n" );
}

/****************************************************************************/
void print_mat( matrix m )
{
	printf( "\n%9f %9f %9f - %9f\n", m[0][0], m[0][1], m[0][2],
			sqrt( m[0][0] * m[0][0] + m[0][1] * m[0][1] + m[0][2] * m[0][2] ));
	printf( "%9f %9f %9f - %9f\n", m[1][0], m[1][1], m[1][2],
			sqrt( m[1][0] * m[1][0] + m[1][1] * m[1][1] + m[1][2] * m[1][2] ));
	printf( "%9f %9f %9f - %9f\n", m[2][0], m[2][1], m[2][2],
			sqrt( m[2][0] * m[2][0] + m[2][1] * m[2][1] + m[2][2] * m[2][2] ));
}

/****************************************************************************/
void print_quat( quat q )
{
	printf( "\n%9f %9f %9f %9f - %9f\n", q[0], q[1], q[2], q[3],
			sqrt( q[0] * q[0] + q[1] * q[1] + q[2] * q[2] + q[3] * q[3] ));
}

/****************************************************************************/
// if -p is a better match to q, set p to -p.
void adjust_quat( quat p, quat q )
{
	float	pdq,npdq;

	pdq = (p[0]-q[0])*(p[0]-q[0]) +
			(p[1]-q[1])*(p[1]-q[1]) +
			(p[2]-q[2])*(p[2]-q[2]) +
			(p[3]-q[3])*(p[3]-q[3]);

	npdq = (p[0]+q[0])*(p[0]+q[0]) +
			(p[1]+q[1])*(p[1]+q[1]) +
			(p[2]+q[2])*(p[2]+q[2]) +
			(p[3]+q[3])*(p[3]+q[3]);

	if( npdq < pdq )
	{
		p[0] *= -1.0f;
		p[1] *= -1.0f;
		p[2] *= -1.0f;
		p[3] *= -1.0f;
	}
}

/****************************************************************************/
