/*
 *		$Archive: /video/tools/tweakd/tweakd.c $
 *		$Revision: 2 $
 *		$Date: 3/04/98 3:16p $
 *
 *		Copyright (c) 1997, 1998 Midway Games Inc.
 *		All Rights Reserved
 *
 *		This file is confidential and a trade secret of Midway Games Inc.
 *		Use, reproduction, adaptation, distribution, performance or
 *		display of this computer program or the associated audiovisual work
 *		is strictly forbidden unless approved in writing by Midway Games Inc.
 */

#ifdef INCLUDE_SSID
char *ss_tweakd_c = "$Workfile: tweakd.c $ $Revision: 2 $";
#endif

/*
 *		SYSTEM INCLUDES
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*
 *		STATIC PROTOTYPES
 */

static int tweakd(char *prog_name, char *d_fname);
static char *strip_path(char *fname);

/*
 *		GLOBAL FUNCTIONS
 */

int main(int argc, char *argv[])
{
	int ret;
	
	if (argc != 2) {
		printf("usage:%s file.d\n", argv[0]);
		ret = EXIT_FAILURE;
	} else
		ret = tweakd(argv[0], argv[1]);
	return ret;
}	/* main */

/*
 *		STATIC FUNCTIONS
 */

static int tweakd(char *prog_name, char *d_fname)
{
	FILE *d_file;
	FILE *new_d_file;
	char tmp_d_fname[L_tmpnam];
	int ret, ch, found_colon;
	
	ret = EXIT_FAILURE;
	d_file = fopen(d_fname, "r");
	if (d_file != NULL) {
		tmpnam(tmp_d_fname);
		new_d_file = fopen(tmp_d_fname, "w");
		if (new_d_file != NULL) {
			found_colon = 0;
			while ((ch = getc(d_file)) != EOF) {
				if ((ch == ':') && (found_colon == 0)) {
					fprintf(new_d_file, " %s:", strip_path(d_fname));
					found_colon = 1;
				} else
					putc(ch, new_d_file);
			}
			fclose(d_file);
			fclose(new_d_file);
			if (remove(d_fname) == 0) {
				ret = EXIT_SUCCESS;
				if (rename(tmp_d_fname, d_fname) != 0) {
					char buffer[1024];
					int cnt;
					
					d_file = fopen(tmp_d_fname, "rb");
					new_d_file = fopen(d_fname, "wb");
					while (!feof(d_file)) {
						cnt = fread(buffer, 1, sizeof(buffer), d_file);
						if (cnt != fwrite(buffer, 1, cnt, new_d_file)) {
							fprintf(stderr, "%s had a fwrite fail while copying dependancy file %s\n", prog_name, d_fname);
							ret = EXIT_FAILURE;
							break;
						}
					}
					fclose(d_file);
					fclose(new_d_file);
					remove(ret == EXIT_SUCCESS ? tmp_d_fname : d_fname);
				}
			} else {
				remove(tmp_d_fname);
				fprintf(stderr, "%s could not remove the dependancy file %s\n", prog_name, d_fname);
			}
		} else {
			fclose(d_file);
			fprintf(stderr, "%s could not create the temp dependancy file %s\n", prog_name, tmp_d_fname);
		}
	} else
		fprintf(stderr, "%s could not open the dependancy file %s\n", prog_name, d_fname);
	return ret;
}	/* tweakd */

static char *strip_path(char *fname)
{
	char *ptr;
	
	ptr = strrchr(fname, '/');
	if (ptr == NULL) {
		ptr = strrchr(fname, '\\');
		if (ptr == NULL)
			ptr = fname;
	}
	return ptr;
}	/* strip_path */

/*
 *		$History: tweakd.c $
 * 
 * *****************  Version 2  *****************
 * User: Markg        Date: 3/04/98    Time: 3:16p
 * Updated in $/video/tools/tweakd
 * Ignore all colons after first one.
 * 
 * *****************  Version 1  *****************
 * User: Markg        Date: 3/04/98    Time: 12:29p
 * Created in $/video/tools/tweakd
 * Utility to tweak the dependancy files generated by GCC
 */

/*
 *	Local Variables:
 *	tab-width:4
 *	End:
 */
