#include	<stdio.h>
#include	<math.h>
#include	<string.h>
#include	<ctype.h>
#include	<stdlib.h>

int	gamma_table[256];
char	line_buffer[256];
double	gamma_val = -1.0;

char	*usage_strs[] = {
"\n\n",
"USAGE: gammagen <gamma_in_file> <out_file_name>\n"
};

char	*title_strs[]= {
"\n\n\n",
"GAMMAGEN\n",
"Version 1.00\n\n"
};

static void show_usage(void)
{
	unsigned int	i;

	for(i = 0; i < sizeof(usage_strs)/sizeof(void *); i++)
	{
		printf("%s", usage_strs[i]);
	}
}

static void show_title_page(void)
{
	unsigned int	i;

	for(i = 0; i < sizeof(title_strs)/sizeof(void *); i++)
	{
		printf("%s", title_strs[i]);
	}
}

void write_gamma_file_header(char *fname, double gamma, FILE *fp)
{
	char	*tmp;

	fprintf(fp, "/*\n");
	fprintf(fp, "** ");
	tmp = rindex(fname, '/');
	if(!tmp)
	{
		tmp = fname;
	}
	else
	{
		++tmp;
	}
	fprintf(fp, "File:  %s\n", fname);
	fprintf(fp, "**\n");
	fprintf(fp, "** File generated by GAMMAGEN using gamma of: %f\n", gamma);
	fprintf(fp, "**\n");
	fprintf(fp, "** DO NOT EDIT\n");
	fprintf(fp, "**\n");
	fprintf(fp, "*/\n\n");
}

void gen_gamma_table(double gamma)
{
	unsigned int	i;

	gamma = 1.0/gamma;
	for(i = 0; i < sizeof(gamma_table)/sizeof(int); i++)
	{
		gamma_table[i] = (int)(pow(i/255.0, gamma) * 255.0 + 0.5);
	}
}

void write_gamma_table(double gamma, FILE *fp)
{
	unsigned int	i;

	gen_gamma_table(gamma);
	fprintf(fp, "int	gamma_table[] = {\n");
	for(i = 0; i < sizeof(gamma_table)/sizeof(int); i++)
	{
		fprintf(fp, "% 4d", gamma_table[i]);
		if(i < (sizeof(gamma_table)/sizeof(int)) - 1)
		{
			fprintf(fp, ", ");
		}
		if(!((i+1)%8) && i < (sizeof(gamma_table)/sizeof(int)) - 1)
		{
			fprintf(fp, "\\\n");
		}
	}
	fprintf(fp, "\n};\n");
}

void get_gamma_val(FILE *fp)
{
	char	*tmp;
	char	*num_ptr;

	while((tmp = fgets(line_buffer, 256, fp)) != NULL)
	{
		if((tmp = strstr(line_buffer, "GAMMA")) != (char *)0)
		{
			if(tmp == line_buffer)
			{
				tmp = index(line_buffer, '=');
				if(!tmp)
				{
					return;
				}
				while(!isdigit(*tmp))
				{
					++tmp;
				}
				num_ptr = tmp;
				while(isdigit(*tmp) || *tmp == '.')
				{
					++tmp;
				}
				*tmp = 0;
				gamma_val = atof(num_ptr);
				return;
			}
		}
	}
}

int main(int argc, char *argv[])
{
	FILE	*in_fp;
	FILE	*out_fp;

	if(argc < 3)
	{
		show_usage();
		return(1);
	}
	show_title_page();
	if((in_fp = fopen(argv[1], "rb")) == (FILE *)0)
	{
		fprintf(stderr, "\nCan not open input file: %s\n", argv[1]);
		return(1);
	}
	get_gamma_val(in_fp);
	if(gamma_val < 0.0)
	{
		fprintf(stderr, "\nGAMMA value not found in file: %s\n", argv[1]);
		fclose(in_fp);
		return(1);
	}
	fclose(in_fp);
	if((out_fp = fopen(argv[2], "wb")) == (FILE *)0)
	{
		fprintf(stderr, "\nCan not open output file: %s\n", argv[2]);
		return(1);
	}
	write_gamma_file_header(argv[2], gamma_val, out_fp);
	write_gamma_table(gamma_val, out_fp);
	fflush(out_fp);
	fclose(out_fp);
	fprintf(stderr, "\nGamma file \"%s\" created\n", argv[2]);
	return(0);
}
