#
# Assorted directories
#
INCDIR=		/video/include/glide
BUILDDIR=	..

#
# Include files everyone is dependant on
#
INCS=	$(INCDIR)/glide.h

#
# C Source Modules
#
CSRCS=	gammagen.c

#
# Object Modules
#
OBJS=	$(CSRCS:.c=.obj)

#
# What we are going to build
#
TARGET=	$(BUILDDIR)/gammagen.exe

#
# This gets built if nothing is specified on the command line
#
all:	$(TARGET) dummy

#
# Dummy target
#
dummy:
	@echo GAMMAGEN DONE

#
# Module rules and dependencies
#
$(BUILDDIR)/gammagen.exe:	$(OBJS)
	@echo Linking $<
	@gcc -O3 -I$(INCDIR) -o $(BUILDDIR)/gammagen.exe $(OBJS)
	@echo $(BUILDDIR)\gammagen.exe built

#
# Rules and dependencies
#
%.d:	%.c
	@echo Generating dependencies for $<
	@gcc -M -I$(INCDIR) $< | sed 's/$*.o/&bj $@/g' > $@

%.obj:	%.c
	@echo Compiling $<
	@gcc -c -O3 -I$(INCDIR) -o $@ $<

include	$(CSRCS:.c=.d)

#
# How to clean up for a complete rebuild
#
clean:	clobber
	@echo Cleaning gammagen
	@if EXIST gammagen.obj del gammagen.obj
	@if EXIST gammagen.d del gammagen.d

#
# How to clean up for a relink only
#
clobber:
	@echo Clobbering $(BUILDDIR)\gammagen.exe
	@if EXIST $(BUILDDIR)\gammagen.exe del $(BUILDDIR)\gammagen.exe

#
# How to rebuild the whole works from scratch
#
rebuild:	clean
	@echo Rebuilding $(BUILDDIR)\gammagen.exe
	@$(MAKE) --no-print-directory

	
